In [52]:
import plotly 
plotly.tools.set_credentials_file(username='yuxiangling0809', api_key='vJxzgz9EZWkJZdHur9A8')

In [53]:
import plotly 
plotly.tools.set_config_file(world_readable=True,
                             sharing='public')

In [54]:
import plotly.plotly as py

In [55]:
from plotly.graph_objs import *

In [56]:
import pandas as pd

In [57]:
df = pd.read_csv('/Users/qiqi/DV590/Part2-Q3-data.csv')

In [58]:
df.head()

   "States, z" locations                                     "States, text"
0       156750        AL  State: AL<br>Total Awarded Amount: 5743215<br>...
1        40063        AK  State: AK<br>Total Awarded Amount: 16189749<br...
2       227358        AZ  State: AZ<br>Total Awarded Amount: 19037687<br...
3        90319        AR  State: AR<br>Total Awarded Amount: 1965330<br>...
4      1766693        CA  State: CA<br>Total Awarded Amount: 74663752<br...

In [59]:
trace1 = {
  "z": [156750,40063,227358,90319,1766693,220454,210170,53247,83586,700267,388342,58573,47176,586442,245197,123353,104884,143875,199683,46277,263809,345059,395166,243933,81678,224091,30637,73455,118785,57282,443148,74403,1023433,357168,24622,467392,125243,147535,506505,45663,143585,31380,227505,990054,94475,23539,359273,296403,53453,226325,27454], 
  "colorbar": {
    "x": 0, 
    "y": 0.5, 
    "outlinecolor": "white", 
    "showexponent": "last", 
    "title": "GDP Distribution (State-level)"
  }, 
  "hoverinfo": "text", 
  "locationmode": "USA-states", 
  "locations": ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"], 
  "marker": {"line": {
      "color": "rgb(255,255,255)", 
      "width": 1
    }}, 
  "name": "States", 
  "text": ["State: AL<br>Total Awarded Amount: 5743215<br>GDP(million):   156750",
"State: AK<br>Total Awarded Amount: 16189749<br>GDP(million): 40063",
"State: AZ<br>Total Awarded Amount: 19037687<br>GDP(million): 227358",
"State: AR<br>Total Awarded Amount: 1965330<br>GDP(million): 90319",
"State: CA<br>Total Awarded Amount: 74663752<br>GDP(million): 1766693",
"State: CO<br>Total Awarded Amount: 22235728<br>GDP(million): 220454",
"State: CT<br>Total Awarded Amount: 16501999<br>GDP(million): 210170",
"State: DE<br>Total Awarded Amount: 3857523<br>GDP(million): 53247",
"State: DC<br>Total Awarded Amount: 25424106<br>GDP(million): 83586",
"State: FL<br>Total Awarded Amount: 26600593<br>GDP(million): 700267",
"State: GA<br>Total Awarded Amount: 11216327<br>GDP(million): 388342",
"State: HI<br>Total Awarded Amount: 14427899<br>GDP(million): 58573",
"State: ID<br>Total Awarded Amount: 1961349<br>GDP(million): 47176",
"State: IL<br>Total Awarded Amount: 68112505<br>GDP(million): 586442",
"State: IN<br>Total Awarded Amount: 16377153<br>GDP(million): 245197",
"State: IA<br>Total Awarded Amount: 8493716<br>GDP(million): 123353",
"State: KS<br>Total Awarded Amount: 5764416<br>GDP(million): 104884",
"State: KY<br>Total Awarded Amount: 8022942<br>GDP(million): 143875",
"State: LA<br>Total Awarded Amount: 7978539<br>GDP(million): 199683",
"State: ME<br>Total Awarded Amount: 11177079<br>GDP(million): 46277",
"State: MD<br>Total Awarded Amount: 21671260<br>GDP(million): 263809",
"State: MA<br>Total Awarded Amount: 45976945<br>GDP(million): 345059",
"State: MI<br>Total Awarded Amount: 28799226<br>GDP(million): 395166",
"State: MN<br>Total Awarded Amount: 15325162<br>GDP(million): 243933",
"State: MS<br>Total Awarded Amount: 2787779<br>GDP(million): 81678",
"State: MO<br>Total Awarded Amount: 14911587<br>GDP(million): 224091",
"State: MT<br>Total Awarded Amount: 10424194<br>GDP(million): 30637",
"State: NE<br>Total Awarded Amount: 6600356<br>GDP(million): 73455",
"State: NV<br>Total Awarded Amount: 3677624<br>GDP(million): 118785",
"State: NH<br>Total Awarded Amount: 4797223<br>GDP(million): 57282",
"State: NJ<br>Total Awarded Amount: 11475362<br>GDP(million): 443148",
"State: NM<br>Total Awarded Amount: 10640574<br>GDP(million): 74403",
"State: NY<br>Total Awarded Amount: 105860170<br>GDP(million): 1023433",
"State: NC<br>Total Awarded Amount: 29992038<br>GDP(million): 357168",
"State: ND<br>Total Awarded Amount: 3071608<br>GDP(million): 24622",
"State: OH<br>Total Awarded Amount: 22015009<br>GDP(million): 467392",
"State: OK<br>Total Awarded Amount: 12405823<br>GDP(million): 125243",
"State: OR<br>Total Awarded Amount: 9556529<br>GDP(million): 147535",
"State: PA<br>Total Awarded Amount: 59575053<br>GDP(million): 506505",
"State: RI<br>Total Awarded Amount: 4751919<br>GDP(million): 45663",
"State: SC<br>Total Awarded Amount: 9063478<br>GDP(million): 143585",
"State: SD<br>Total Awarded Amount: 3596551<br>GDP(million): 31380",
"State: TN<br>Total Awarded Amount: 18083590<br>GDP(million): 227505",
"State: TX<br>Total Awarded Amount: 48252344<br>GDP(million): 990054",
"State: UT<br>Total Awarded Amount: 6884351<br>GDP(million): 94475",
"State: VT<br>Total Awarded Amount: 6381133<br>GDP(million): 23539",
"State: VA<br>Total Awarded Amount: 18068081<br>GDP(million): 359273",
"State: WA<br>Total Awarded Amount: 23476750<br>GDP(million): 296403",
"State: WV<br>Total Awarded Amount: 927680<br>GDP(million): 53453",
"State: WI<br>Total Awarded Amount: 17075827<br>GDP(million): 226325",
"State: WY<br>Total Awarded Amount: 2210361<br>GDP(million): 27454]"],
  "type": "choropleth", 
  "uid": "dafa1f", 
  "zmax": 1766693, 
  "zmin": 23539
}

In [60]:
trace2 = {
  "hoverinfo": "text", 
  "lat": [33.448, 29.954, 42.373611, 38.328732, 43.038902, 41.85, 39.768, 47.606, 33.792461, 39.29, 38.627, 44.979, 40.73061, 37.774, 37.339, 40.44, 34.052, 25.774, 29.763, 42.886], 
  "locationmode": "USA-states", 
  "lon": [-112.066667, -90.066667, -71.110556, -85.764771, -87.906471, -87.684722, -86.15, -122.333056, -118.185005, -76.616667, -90.197778, -93.266667, -73.935242, -122.416667, -121.9, -79.976389, -118.25, -80.208889, -95.383056, -78.849444], 
  "marker": {
    "color": "yellow", 
    "line": {
      "color": "orange", 
      "width": 1
    }, 
    "opacity": 0.1, 
    "size": [34.125, 28.875, 27.75, 27.75, 27.75, 27.5, 25, 14.75, 13.875, 13.125, 12.5, 12.5, 12.25, 12.25, 11.375, 11.375, 10.875, 9.625, 8.375, 7.75]
  }, 
  "showlegend": False, 
 "text": ["State: AL<br>Total Awarded Amount: 5743215<br>GDP(million):   156750",
"State: AK<br>Total Awarded Amount: 16189749<br>GDP(million): 40063",
"State: AZ<br>Total Awarded Amount: 19037687<br>GDP(million): 227358",
"State: AR<br>Total Awarded Amount: 1965330<br>GDP(million): 90319",
"State: CA<br>Total Awarded Amount: 74663752<br>GDP(million): 1766693",
"State: CO<br>Total Awarded Amount: 22235728<br>GDP(million): 220454",
"State: CT<br>Total Awarded Amount: 16501999<br>GDP(million): 210170",
"State: DE<br>Total Awarded Amount: 3857523<br>GDP(million): 53247",
"State: DC<br>Total Awarded Amount: 25424106<br>GDP(million): 83586",
"State: FL<br>Total Awarded Amount: 26600593<br>GDP(million): 700267",
"State: GA<br>Total Awarded Amount: 11216327<br>GDP(million): 388342",
"State: HI<br>Total Awarded Amount: 14427899<br>GDP(million): 58573",
"State: ID<br>Total Awarded Amount: 1961349<br>GDP(million): 47176",
"State: IL<br>Total Awarded Amount: 68112505<br>GDP(million): 586442",
"State: IN<br>Total Awarded Amount: 16377153<br>GDP(million): 245197",
"State: IA<br>Total Awarded Amount: 8493716<br>GDP(million): 123353",
"State: KS<br>Total Awarded Amount: 5764416<br>GDP(million): 104884",
"State: KY<br>Total Awarded Amount: 8022942<br>GDP(million): 143875",
"State: LA<br>Total Awarded Amount: 7978539<br>GDP(million): 199683",
"State: ME<br>Total Awarded Amount: 11177079<br>GDP(million): 46277",
"State: MD<br>Total Awarded Amount: 21671260<br>GDP(million): 263809",
"State: MA<br>Total Awarded Amount: 45976945<br>GDP(million): 345059",
"State: MI<br>Total Awarded Amount: 28799226<br>GDP(million): 395166",
"State: MN<br>Total Awarded Amount: 15325162<br>GDP(million): 243933",
"State: MS<br>Total Awarded Amount: 2787779<br>GDP(million): 81678",
"State: MO<br>Total Awarded Amount: 14911587<br>GDP(million): 224091",
"State: MT<br>Total Awarded Amount: 10424194<br>GDP(million): 30637",
"State: NE<br>Total Awarded Amount: 6600356<br>GDP(million): 73455",
"State: NV<br>Total Awarded Amount: 3677624<br>GDP(million): 118785",
"State: NH<br>Total Awarded Amount: 4797223<br>GDP(million): 57282",
"State: NJ<br>Total Awarded Amount: 11475362<br>GDP(million): 443148",
"State: NM<br>Total Awarded Amount: 10640574<br>GDP(million): 74403",
"State: NY<br>Total Awarded Amount: 105860170<br>GDP(million): 1023433",
"State: NC<br>Total Awarded Amount: 29992038<br>GDP(million): 357168",
"State: ND<br>Total Awarded Amount: 3071608<br>GDP(million): 24622",
"State: OH<br>Total Awarded Amount: 22015009<br>GDP(million): 467392",
"State: OK<br>Total Awarded Amount: 12405823<br>GDP(million): 125243",
"State: OR<br>Total Awarded Amount: 9556529<br>GDP(million): 147535",
"State: PA<br>Total Awarded Amount: 59575053<br>GDP(million): 506505",
"State: RI<br>Total Awarded Amount: 4751919<br>GDP(million): 45663",
"State: SC<br>Total Awarded Amount: 9063478<br>GDP(million): 143585",
"State: SD<br>Total Awarded Amount: 3596551<br>GDP(million): 31380",
"State: TN<br>Total Awarded Amount: 18083590<br>GDP(million): 227505",
"State: TX<br>Total Awarded Amount: 48252344<br>GDP(million): 990054",
"State: UT<br>Total Awarded Amount: 6884351<br>GDP(million): 94475",
"State: VT<br>Total Awarded Amount: 6381133<br>GDP(million): 23539",
"State: VA<br>Total Awarded Amount: 18068081<br>GDP(million): 359273",
"State: WA<br>Total Awarded Amount: 23476750<br>GDP(million): 296403",
"State: WV<br>Total Awarded Amount: 927680<br>GDP(million): 53453",
"State: WI<br>Total Awarded Amount: 17075827<br>GDP(million): 226325",
"State: WY<br>Total Awarded Amount: 2210361<br>GDP(million): 27454]"],
  "type": "scattergeo", 
  "uid": "637ddb"
}

In [61]:
trace3 = {
  "hoverinfo": "text", 
  "lat": [33.448, 29.954, 42.373611, 38.328732, 43.038902, 41.85, 39.768, 47.606, 33.792461, 39.29, 38.627, 44.979, 40.73061, 37.774, 37.339, 40.44, 34.052, 25.774, 29.763, 42.886], 
  "locationmode": "USA-states", 
  "lon": [-112.066667, -90.066667, -71.110556, -85.764771, -87.906471, -87.684722, -86.15, -122.333056, -118.185005, -76.616667, -90.197778, -93.266667, -73.935242, -122.416667, -121.9, -79.976389, -118.25, -80.208889, -95.383056, -78.849444], 
  "marker": {
    "color": "yellow", 
    "line": {
      "color": "orange", 
      "width": 1
    }, 
    "opacity": 0.1, 
    "size": [34.125, 28.875, 27.75, 27.75, 27.75, 27.5, 25, 14.75, 13.875, 13.125, 12.5, 12.5, 12.25, 12.25, 11.375, 11.375, 10.875, 9.625, 8.375, 7.75]
  }, 
  "showlegend": False, 
 "text": ["State: AL<br>Total Awarded Amount: 5743215<br>GDP(million):   156750",
"State: AK<br>Total Awarded Amount: 16189749<br>GDP(million): 40063",
"State: AZ<br>Total Awarded Amount: 19037687<br>GDP(million): 227358",
"State: AR<br>Total Awarded Amount: 1965330<br>GDP(million): 90319",
"State: CA<br>Total Awarded Amount: 74663752<br>GDP(million): 1766693",
"State: CO<br>Total Awarded Amount: 22235728<br>GDP(million): 220454",
"State: CT<br>Total Awarded Amount: 16501999<br>GDP(million): 210170",
"State: DE<br>Total Awarded Amount: 3857523<br>GDP(million): 53247",
"State: DC<br>Total Awarded Amount: 25424106<br>GDP(million): 83586",
"State: FL<br>Total Awarded Amount: 26600593<br>GDP(million): 700267",
"State: GA<br>Total Awarded Amount: 11216327<br>GDP(million): 388342",
"State: HI<br>Total Awarded Amount: 14427899<br>GDP(million): 58573",
"State: ID<br>Total Awarded Amount: 1961349<br>GDP(million): 47176",
"State: IL<br>Total Awarded Amount: 68112505<br>GDP(million): 586442",
"State: IN<br>Total Awarded Amount: 16377153<br>GDP(million): 245197",
"State: IA<br>Total Awarded Amount: 8493716<br>GDP(million): 123353",
"State: KS<br>Total Awarded Amount: 5764416<br>GDP(million): 104884",
"State: KY<br>Total Awarded Amount: 8022942<br>GDP(million): 143875",
"State: LA<br>Total Awarded Amount: 7978539<br>GDP(million): 199683",
"State: ME<br>Total Awarded Amount: 11177079<br>GDP(million): 46277",
"State: MD<br>Total Awarded Amount: 21671260<br>GDP(million): 263809",
"State: MA<br>Total Awarded Amount: 45976945<br>GDP(million): 345059",
"State: MI<br>Total Awarded Amount: 28799226<br>GDP(million): 395166",
"State: MN<br>Total Awarded Amount: 15325162<br>GDP(million): 243933",
"State: MS<br>Total Awarded Amount: 2787779<br>GDP(million): 81678",
"State: MO<br>Total Awarded Amount: 14911587<br>GDP(million): 224091",
"State: MT<br>Total Awarded Amount: 10424194<br>GDP(million): 30637",
"State: NE<br>Total Awarded Amount: 6600356<br>GDP(million): 73455",
"State: NV<br>Total Awarded Amount: 3677624<br>GDP(million): 118785",
"State: NH<br>Total Awarded Amount: 4797223<br>GDP(million): 57282",
"State: NJ<br>Total Awarded Amount: 11475362<br>GDP(million): 443148",
"State: NM<br>Total Awarded Amount: 10640574<br>GDP(million): 74403",
"State: NY<br>Total Awarded Amount: 105860170<br>GDP(million): 1023433",
"State: NC<br>Total Awarded Amount: 29992038<br>GDP(million): 357168",
"State: ND<br>Total Awarded Amount: 3071608<br>GDP(million): 24622",
"State: OH<br>Total Awarded Amount: 22015009<br>GDP(million): 467392",
"State: OK<br>Total Awarded Amount: 12405823<br>GDP(million): 125243",
"State: OR<br>Total Awarded Amount: 9556529<br>GDP(million): 147535",
"State: PA<br>Total Awarded Amount: 59575053<br>GDP(million): 506505",
"State: RI<br>Total Awarded Amount: 4751919<br>GDP(million): 45663",
"State: SC<br>Total Awarded Amount: 9063478<br>GDP(million): 143585",
"State: SD<br>Total Awarded Amount: 3596551<br>GDP(million): 31380",
"State: TN<br>Total Awarded Amount: 18083590<br>GDP(million): 227505",
"State: TX<br>Total Awarded Amount: 48252344<br>GDP(million): 990054",
"State: UT<br>Total Awarded Amount: 6884351<br>GDP(million): 94475",
"State: VT<br>Total Awarded Amount: 6381133<br>GDP(million): 23539",
"State: VA<br>Total Awarded Amount: 18068081<br>GDP(million): 359273",
"State: WA<br>Total Awarded Amount: 23476750<br>GDP(million): 296403",
"State: WV<br>Total Awarded Amount: 927680<br>GDP(million): 53453",
"State: WI<br>Total Awarded Amount: 17075827<br>GDP(million): 226325",
"State: WY<br>Total Awarded Amount: 2210361<br>GDP(million): 27454]"],
  "type": "scattergeo", 
  "uid": "2bdf0d"
}

In [62]:
trace4 = {
  "hoverinfo": "text", 
  "lat": [33.448, 29.954, 42.373611, 38.328732, 43.038902, 41.85, 39.768, 47.606, 33.792461, 39.29, 38.627, 44.979, 40.73061, 37.774, 37.339, 40.44, 34.052, 25.774, 29.763, 42.886], 
  "locationmode": "USA-states", 
  "lon": [-112.066667, -90.066667, -71.110556, -85.764771, -87.906471, -87.684722, -86.15, -122.333056, -118.185005, -76.616667, -90.197778, -93.266667, -73.935242, -122.416667, -121.9, -79.976389, -118.25, -80.208889, -95.383056, -78.849444], 
  "marker": {
    "color": "yellow", 
    "line": {
      "color": "orange", 
      "width": 1
    }, 
    "opacity": 0.1, 
    "size": [34.125, 28.875, 27.75, 27.75, 27.75, 27.5, 25, 14.75, 13.875, 13.125, 12.5, 12.5, 12.25, 12.25, 11.375, 11.375, 10.875, 9.625, 8.375, 7.75]
  }, 
  "showlegend": False, 
 "text": ["State: AL<br>Total Awarded Amount: 5743215<br>GDP(million):   156750",
"State: AK<br>Total Awarded Amount: 16189749<br>GDP(million): 40063",
"State: AZ<br>Total Awarded Amount: 19037687<br>GDP(million): 227358",
"State: AR<br>Total Awarded Amount: 1965330<br>GDP(million): 90319",
"State: CA<br>Total Awarded Amount: 74663752<br>GDP(million): 1766693",
"State: CO<br>Total Awarded Amount: 22235728<br>GDP(million): 220454",
"State: CT<br>Total Awarded Amount: 16501999<br>GDP(million): 210170",
"State: DE<br>Total Awarded Amount: 3857523<br>GDP(million): 53247",
"State: DC<br>Total Awarded Amount: 25424106<br>GDP(million): 83586",
"State: FL<br>Total Awarded Amount: 26600593<br>GDP(million): 700267",
"State: GA<br>Total Awarded Amount: 11216327<br>GDP(million): 388342",
"State: HI<br>Total Awarded Amount: 14427899<br>GDP(million): 58573",
"State: ID<br>Total Awarded Amount: 1961349<br>GDP(million): 47176",
"State: IL<br>Total Awarded Amount: 68112505<br>GDP(million): 586442",
"State: IN<br>Total Awarded Amount: 16377153<br>GDP(million): 245197",
"State: IA<br>Total Awarded Amount: 8493716<br>GDP(million): 123353",
"State: KS<br>Total Awarded Amount: 5764416<br>GDP(million): 104884",
"State: KY<br>Total Awarded Amount: 8022942<br>GDP(million): 143875",
"State: LA<br>Total Awarded Amount: 7978539<br>GDP(million): 199683",
"State: ME<br>Total Awarded Amount: 11177079<br>GDP(million): 46277",
"State: MD<br>Total Awarded Amount: 21671260<br>GDP(million): 263809",
"State: MA<br>Total Awarded Amount: 45976945<br>GDP(million): 345059",
"State: MI<br>Total Awarded Amount: 28799226<br>GDP(million): 395166",
"State: MN<br>Total Awarded Amount: 15325162<br>GDP(million): 243933",
"State: MS<br>Total Awarded Amount: 2787779<br>GDP(million): 81678",
"State: MO<br>Total Awarded Amount: 14911587<br>GDP(million): 224091",
"State: MT<br>Total Awarded Amount: 10424194<br>GDP(million): 30637",
"State: NE<br>Total Awarded Amount: 6600356<br>GDP(million): 73455",
"State: NV<br>Total Awarded Amount: 3677624<br>GDP(million): 118785",
"State: NH<br>Total Awarded Amount: 4797223<br>GDP(million): 57282",
"State: NJ<br>Total Awarded Amount: 11475362<br>GDP(million): 443148",
"State: NM<br>Total Awarded Amount: 10640574<br>GDP(million): 74403",
"State: NY<br>Total Awarded Amount: 105860170<br>GDP(million): 1023433",
"State: NC<br>Total Awarded Amount: 29992038<br>GDP(million): 357168",
"State: ND<br>Total Awarded Amount: 3071608<br>GDP(million): 24622",
"State: OH<br>Total Awarded Amount: 22015009<br>GDP(million): 467392",
"State: OK<br>Total Awarded Amount: 12405823<br>GDP(million): 125243",
"State: OR<br>Total Awarded Amount: 9556529<br>GDP(million): 147535",
"State: PA<br>Total Awarded Amount: 59575053<br>GDP(million): 506505",
"State: RI<br>Total Awarded Amount: 4751919<br>GDP(million): 45663",
"State: SC<br>Total Awarded Amount: 9063478<br>GDP(million): 143585",
"State: SD<br>Total Awarded Amount: 3596551<br>GDP(million): 31380",
"State: TN<br>Total Awarded Amount: 18083590<br>GDP(million): 227505",
"State: TX<br>Total Awarded Amount: 48252344<br>GDP(million): 990054",
"State: UT<br>Total Awarded Amount: 6884351<br>GDP(million): 94475",
"State: VT<br>Total Awarded Amount: 6381133<br>GDP(million): 23539",
"State: VA<br>Total Awarded Amount: 18068081<br>GDP(million): 359273",
"State: WA<br>Total Awarded Amount: 23476750<br>GDP(million): 296403",
"State: WV<br>Total Awarded Amount: 927680<br>GDP(million): 53453",
"State: WI<br>Total Awarded Amount: 17075827<br>GDP(million): 226325",
"State: WY<br>Total Awarded Amount: 2210361<br>GDP(million): 27454]"],
  "type": "scattergeo", 
  "uid": "6ce964"
}

In [63]:
trace5 = {
  "hoverinfo": "text", 
  "lat": [33.448, 29.954, 42.373611, 38.328732, 43.038902, 41.85, 39.768, 47.606, 33.792461, 39.29, 38.627, 44.979, 40.73061, 37.774, 37.339, 40.44, 34.052, 25.774, 29.763, 42.886], 
  "locationmode": "USA-states", 
  "lon": [-112.066667, -90.066667, -71.110556, -85.764771, -87.906471, -87.684722, -86.15, -122.333056, -118.185005, -76.616667, -90.197778, -93.266667, -73.935242, -122.416667, -121.9, -79.976389, -118.25, -80.208889, -95.383056, -78.849444], 
  "marker": {
    "color": "yellow", 
    "line": {
      "color": "orange", 
      "width": 1
    }, 
    "opacity": 0.1, 
    "size": [34.125, 28.875, 27.75, 27.75, 27.75, 27.5, 25, 14.75, 13.875, 13.125, 12.5, 12.5, 12.25, 12.25, 11.375, 11.375, 10.875, 9.625, 8.375, 7.75]
  }, 
  "showlegend": False,
  "text": ["State: AL<br>Total Awarded Amount: 5743215<br>GDP(million):   156750",
"State: AK<br>Total Awarded Amount: 16189749<br>GDP(million): 40063",
"State: AZ<br>Total Awarded Amount: 19037687<br>GDP(million): 227358",
"State: AR<br>Total Awarded Amount: 1965330<br>GDP(million): 90319",
"State: CA<br>Total Awarded Amount: 74663752<br>GDP(million): 1766693",
"State: CO<br>Total Awarded Amount: 22235728<br>GDP(million): 220454",
"State: CT<br>Total Awarded Amount: 16501999<br>GDP(million): 210170",
"State: DE<br>Total Awarded Amount: 3857523<br>GDP(million): 53247",
"State: DC<br>Total Awarded Amount: 25424106<br>GDP(million): 83586",
"State: FL<br>Total Awarded Amount: 26600593<br>GDP(million): 700267",
"State: GA<br>Total Awarded Amount: 11216327<br>GDP(million): 388342",
"State: HI<br>Total Awarded Amount: 14427899<br>GDP(million): 58573",
"State: ID<br>Total Awarded Amount: 1961349<br>GDP(million): 47176",
"State: IL<br>Total Awarded Amount: 68112505<br>GDP(million): 586442",
"State: IN<br>Total Awarded Amount: 16377153<br>GDP(million): 245197",
"State: IA<br>Total Awarded Amount: 8493716<br>GDP(million): 123353",
"State: KS<br>Total Awarded Amount: 5764416<br>GDP(million): 104884",
"State: KY<br>Total Awarded Amount: 8022942<br>GDP(million): 143875",
"State: LA<br>Total Awarded Amount: 7978539<br>GDP(million): 199683",
"State: ME<br>Total Awarded Amount: 11177079<br>GDP(million): 46277",
"State: MD<br>Total Awarded Amount: 21671260<br>GDP(million): 263809",
"State: MA<br>Total Awarded Amount: 45976945<br>GDP(million): 345059",
"State: MI<br>Total Awarded Amount: 28799226<br>GDP(million): 395166",
"State: MN<br>Total Awarded Amount: 15325162<br>GDP(million): 243933",
"State: MS<br>Total Awarded Amount: 2787779<br>GDP(million): 81678",
"State: MO<br>Total Awarded Amount: 14911587<br>GDP(million): 224091",
"State: MT<br>Total Awarded Amount: 10424194<br>GDP(million): 30637",
"State: NE<br>Total Awarded Amount: 6600356<br>GDP(million): 73455",
"State: NV<br>Total Awarded Amount: 3677624<br>GDP(million): 118785",
"State: NH<br>Total Awarded Amount: 4797223<br>GDP(million): 57282",
"State: NJ<br>Total Awarded Amount: 11475362<br>GDP(million): 443148",
"State: NM<br>Total Awarded Amount: 10640574<br>GDP(million): 74403",
"State: NY<br>Total Awarded Amount: 105860170<br>GDP(million): 1023433",
"State: NC<br>Total Awarded Amount: 29992038<br>GDP(million): 357168",
"State: ND<br>Total Awarded Amount: 3071608<br>GDP(million): 24622",
"State: OH<br>Total Awarded Amount: 22015009<br>GDP(million): 467392",
"State: OK<br>Total Awarded Amount: 12405823<br>GDP(million): 125243",
"State: OR<br>Total Awarded Amount: 9556529<br>GDP(million): 147535",
"State: PA<br>Total Awarded Amount: 59575053<br>GDP(million): 506505",
"State: RI<br>Total Awarded Amount: 4751919<br>GDP(million): 45663",
"State: SC<br>Total Awarded Amount: 9063478<br>GDP(million): 143585",
"State: SD<br>Total Awarded Amount: 3596551<br>GDP(million): 31380",
"State: TN<br>Total Awarded Amount: 18083590<br>GDP(million): 227505",
"State: TX<br>Total Awarded Amount: 48252344<br>GDP(million): 990054",
"State: UT<br>Total Awarded Amount: 6884351<br>GDP(million): 94475",
"State: VT<br>Total Awarded Amount: 6381133<br>GDP(million): 23539",
"State: VA<br>Total Awarded Amount: 18068081<br>GDP(million): 359273",
"State: WA<br>Total Awarded Amount: 23476750<br>GDP(million): 296403",
"State: WV<br>Total Awarded Amount: 927680<br>GDP(million): 53453",
"State: WI<br>Total Awarded Amount: 17075827<br>GDP(million): 226325",
"State: WY<br>Total Awarded Amount: 2210361<br>GDP(million): 27454]"],
  "type": "scattergeo", 
  "uid": "28256e"
}

In [64]:
trace6 = {
  "hoverinfo": "text", 
  "lat": [33.448, 29.954, 42.373611, 38.328732, 43.038902, 41.85, 39.768, 47.606, 33.792461, 39.29, 38.627, 44.979, 40.73061, 37.774, 37.339, 40.44, 34.052, 25.774, 29.763, 42.886], 
  "locationmode": "USA-states", 
  "lon": [-112.066667, -90.066667, -71.110556, -85.764771, -87.906471, -87.684722, -86.15, -122.333056, -118.185005, -76.616667, -90.197778, -93.266667, -73.935242, -122.416667, -121.9, -79.976389, -118.25, -80.208889, -95.383056, -78.849444], 
  "marker": {
    "color": "yellow", 
    "line": {
      "color": "orange", 
      "width": 1
    }, 
    "opacity": 0.1, 
    "size": [34.125, 28.875, 27.75, 27.75, 27.75, 27.5, 25, 14.75, 13.875, 13.125, 12.5, 12.5, 12.25, 12.25, 11.375, 11.375, 10.875, 9.625, 8.375, 7.75]
  }, 
  "showlegend": False, 
 "text": ["State: AL<br>Total Awarded Amount: 5743215<br>GDP(million):   156750",
"State: AK<br>Total Awarded Amount: 16189749<br>GDP(million): 40063",
"State: AZ<br>Total Awarded Amount: 19037687<br>GDP(million): 227358",
"State: AR<br>Total Awarded Amount: 1965330<br>GDP(million): 90319",
"State: CA<br>Total Awarded Amount: 74663752<br>GDP(million): 1766693",
"State: CO<br>Total Awarded Amount: 22235728<br>GDP(million): 220454",
"State: CT<br>Total Awarded Amount: 16501999<br>GDP(million): 210170",
"State: DE<br>Total Awarded Amount: 3857523<br>GDP(million): 53247",
"State: DC<br>Total Awarded Amount: 25424106<br>GDP(million): 83586",
"State: FL<br>Total Awarded Amount: 26600593<br>GDP(million): 700267",
"State: GA<br>Total Awarded Amount: 11216327<br>GDP(million): 388342",
"State: HI<br>Total Awarded Amount: 14427899<br>GDP(million): 58573",
"State: ID<br>Total Awarded Amount: 1961349<br>GDP(million): 47176",
"State: IL<br>Total Awarded Amount: 68112505<br>GDP(million): 586442",
"State: IN<br>Total Awarded Amount: 16377153<br>GDP(million): 245197",
"State: IA<br>Total Awarded Amount: 8493716<br>GDP(million): 123353",
"State: KS<br>Total Awarded Amount: 5764416<br>GDP(million): 104884",
"State: KY<br>Total Awarded Amount: 8022942<br>GDP(million): 143875",
"State: LA<br>Total Awarded Amount: 7978539<br>GDP(million): 199683",
"State: ME<br>Total Awarded Amount: 11177079<br>GDP(million): 46277",
"State: MD<br>Total Awarded Amount: 21671260<br>GDP(million): 263809",
"State: MA<br>Total Awarded Amount: 45976945<br>GDP(million): 345059",
"State: MI<br>Total Awarded Amount: 28799226<br>GDP(million): 395166",
"State: MN<br>Total Awarded Amount: 15325162<br>GDP(million): 243933",
"State: MS<br>Total Awarded Amount: 2787779<br>GDP(million): 81678",
"State: MO<br>Total Awarded Amount: 14911587<br>GDP(million): 224091",
"State: MT<br>Total Awarded Amount: 10424194<br>GDP(million): 30637",
"State: NE<br>Total Awarded Amount: 6600356<br>GDP(million): 73455",
"State: NV<br>Total Awarded Amount: 3677624<br>GDP(million): 118785",
"State: NH<br>Total Awarded Amount: 4797223<br>GDP(million): 57282",
"State: NJ<br>Total Awarded Amount: 11475362<br>GDP(million): 443148",
"State: NM<br>Total Awarded Amount: 10640574<br>GDP(million): 74403",
"State: NY<br>Total Awarded Amount: 105860170<br>GDP(million): 1023433",
"State: NC<br>Total Awarded Amount: 29992038<br>GDP(million): 357168",
"State: ND<br>Total Awarded Amount: 3071608<br>GDP(million): 24622",
"State: OH<br>Total Awarded Amount: 22015009<br>GDP(million): 467392",
"State: OK<br>Total Awarded Amount: 12405823<br>GDP(million): 125243",
"State: OR<br>Total Awarded Amount: 9556529<br>GDP(million): 147535",
"State: PA<br>Total Awarded Amount: 59575053<br>GDP(million): 506505",
"State: RI<br>Total Awarded Amount: 4751919<br>GDP(million): 45663",
"State: SC<br>Total Awarded Amount: 9063478<br>GDP(million): 143585",
"State: SD<br>Total Awarded Amount: 3596551<br>GDP(million): 31380",
"State: TN<br>Total Awarded Amount: 18083590<br>GDP(million): 227505",
"State: TX<br>Total Awarded Amount: 48252344<br>GDP(million): 990054",
"State: UT<br>Total Awarded Amount: 6884351<br>GDP(million): 94475",
"State: VT<br>Total Awarded Amount: 6381133<br>GDP(million): 23539",
"State: VA<br>Total Awarded Amount: 18068081<br>GDP(million): 359273",
"State: WA<br>Total Awarded Amount: 23476750<br>GDP(million): 296403",
"State: WV<br>Total Awarded Amount: 927680<br>GDP(million): 53453",
"State: WI<br>Total Awarded Amount: 17075827<br>GDP(million): 226325",
"State: WY<br>Total Awarded Amount: 2210361<br>GDP(million): 27454]"],
    "type": "scattergeo", 
  "uid": "af5e65"
}

In [65]:
trace7 = {
  "hoverinfo": "text", 
  "lat": [33.448, 29.954, 42.373611, 38.328732, 43.038902, 41.85, 39.768, 47.606, 33.792461, 39.29, 38.627, 44.979, 40.73061, 37.774, 37.339, 40.44, 34.052, 25.774, 29.763, 42.886], 
  "locationmode": "USA-states", 
  "lon": [-112.066667, -90.066667, -71.110556, -85.764771, -87.906471, -87.684722, -86.15, -122.333056, -118.185005, -76.616667, -90.197778, -93.266667, -73.935242, -122.416667, -121.9, -79.976389, -118.25, -80.208889, -95.383056, -78.849444], 
  "marker": {
    "color": "yellow", 
    "line": {
      "color": "orange", 
      "width": 1
    }, 
    "opacity": 0.1, 
    "size": [34.125, 28.875, 27.75, 27.75, 27.75, 27.5, 25, 14.75, 13.875, 13.125, 12.5, 12.5, 12.25, 12.25, 11.375, 11.375, 10.875, 9.625, 8.375, 7.75]
  }, 
  "showlegend": False, 
 "text": ["State: AL<br>Total Awarded Amount: 5743215<br>GDP(million):   156750",
"State: AK<br>Total Awarded Amount: 16189749<br>GDP(million): 40063",
"State: AZ<br>Total Awarded Amount: 19037687<br>GDP(million): 227358",
"State: AR<br>Total Awarded Amount: 1965330<br>GDP(million): 90319",
"State: CA<br>Total Awarded Amount: 74663752<br>GDP(million): 1766693",
"State: CO<br>Total Awarded Amount: 22235728<br>GDP(million): 220454",
"State: CT<br>Total Awarded Amount: 16501999<br>GDP(million): 210170",
"State: DE<br>Total Awarded Amount: 3857523<br>GDP(million): 53247",
"State: DC<br>Total Awarded Amount: 25424106<br>GDP(million): 83586",
"State: FL<br>Total Awarded Amount: 26600593<br>GDP(million): 700267",
"State: GA<br>Total Awarded Amount: 11216327<br>GDP(million): 388342",
"State: HI<br>Total Awarded Amount: 14427899<br>GDP(million): 58573",
"State: ID<br>Total Awarded Amount: 1961349<br>GDP(million): 47176",
"State: IL<br>Total Awarded Amount: 68112505<br>GDP(million): 586442",
"State: IN<br>Total Awarded Amount: 16377153<br>GDP(million): 245197",
"State: IA<br>Total Awarded Amount: 8493716<br>GDP(million): 123353",
"State: KS<br>Total Awarded Amount: 5764416<br>GDP(million): 104884",
"State: KY<br>Total Awarded Amount: 8022942<br>GDP(million): 143875",
"State: LA<br>Total Awarded Amount: 7978539<br>GDP(million): 199683",
"State: ME<br>Total Awarded Amount: 11177079<br>GDP(million): 46277",
"State: MD<br>Total Awarded Amount: 21671260<br>GDP(million): 263809",
"State: MA<br>Total Awarded Amount: 45976945<br>GDP(million): 345059",
"State: MI<br>Total Awarded Amount: 28799226<br>GDP(million): 395166",
"State: MN<br>Total Awarded Amount: 15325162<br>GDP(million): 243933",
"State: MS<br>Total Awarded Amount: 2787779<br>GDP(million): 81678",
"State: MO<br>Total Awarded Amount: 14911587<br>GDP(million): 224091",
"State: MT<br>Total Awarded Amount: 10424194<br>GDP(million): 30637",
"State: NE<br>Total Awarded Amount: 6600356<br>GDP(million): 73455",
"State: NV<br>Total Awarded Amount: 3677624<br>GDP(million): 118785",
"State: NH<br>Total Awarded Amount: 4797223<br>GDP(million): 57282",
"State: NJ<br>Total Awarded Amount: 11475362<br>GDP(million): 443148",
"State: NM<br>Total Awarded Amount: 10640574<br>GDP(million): 74403",
"State: NY<br>Total Awarded Amount: 105860170<br>GDP(million): 1023433",
"State: NC<br>Total Awarded Amount: 29992038<br>GDP(million): 357168",
"State: ND<br>Total Awarded Amount: 3071608<br>GDP(million): 24622",
"State: OH<br>Total Awarded Amount: 22015009<br>GDP(million): 467392",
"State: OK<br>Total Awarded Amount: 12405823<br>GDP(million): 125243",
"State: OR<br>Total Awarded Amount: 9556529<br>GDP(million): 147535",
"State: PA<br>Total Awarded Amount: 59575053<br>GDP(million): 506505",
"State: RI<br>Total Awarded Amount: 4751919<br>GDP(million): 45663",
"State: SC<br>Total Awarded Amount: 9063478<br>GDP(million): 143585",
"State: SD<br>Total Awarded Amount: 3596551<br>GDP(million): 31380",
"State: TN<br>Total Awarded Amount: 18083590<br>GDP(million): 227505",
"State: TX<br>Total Awarded Amount: 48252344<br>GDP(million): 990054",
"State: UT<br>Total Awarded Amount: 6884351<br>GDP(million): 94475",
"State: VT<br>Total Awarded Amount: 6381133<br>GDP(million): 23539",
"State: VA<br>Total Awarded Amount: 18068081<br>GDP(million): 359273",
"State: WA<br>Total Awarded Amount: 23476750<br>GDP(million): 296403",
"State: WV<br>Total Awarded Amount: 927680<br>GDP(million): 53453",
"State: WI<br>Total Awarded Amount: 17075827<br>GDP(million): 226325",
"State: WY<br>Total Awarded Amount: 2210361<br>GDP(million): 27454]"],
  "type": "scattergeo", 
  "uid": "89649a"
}

In [66]:
trace8 = {
  "hoverinfo": "text", 
  "lat": [33.448, 29.954, 42.373611, 38.328732, 43.038902, 41.85, 39.768, 47.606, 33.792461, 39.29, 38.627, 44.979, 40.73061, 37.774, 37.339, 40.44, 34.052, 25.774, 29.763, 42.886], 
  "locationmode": "USA-states", 
  "lon": [-112.066667, -90.066667, -71.110556, -85.764771, -87.906471, -87.684722, -86.15, -122.333056, -118.185005, -76.616667, -90.197778, -93.266667, -73.935242, -122.416667, -121.9, -79.976389, -118.25, -80.208889, -95.383056, -78.849444], 
  "marker": {
    "color": "yellow", 
    "line": {
      "color": "orange", 
      "width": 1
    }, 
    "opacity": 0.1, 
    "size": [34.125, 28.875, 27.75, 27.75, 27.75, 27.5, 25, 14.75, 13.875, 13.125, 12.5, 12.5, 12.25, 12.25, 11.375, 11.375, 10.875, 9.625, 8.375, 7.75]
  }, 
  "showlegend": False, 
 "text": ["State: AL<br>Total Awarded Amount: 5743215<br>GDP(million):   156750",
"State: AK<br>Total Awarded Amount: 16189749<br>GDP(million): 40063",
"State: AZ<br>Total Awarded Amount: 19037687<br>GDP(million): 227358",
"State: AR<br>Total Awarded Amount: 1965330<br>GDP(million): 90319",
"State: CA<br>Total Awarded Amount: 74663752<br>GDP(million): 1766693",
"State: CO<br>Total Awarded Amount: 22235728<br>GDP(million): 220454",
"State: CT<br>Total Awarded Amount: 16501999<br>GDP(million): 210170",
"State: DE<br>Total Awarded Amount: 3857523<br>GDP(million): 53247",
"State: DC<br>Total Awarded Amount: 25424106<br>GDP(million): 83586",
"State: FL<br>Total Awarded Amount: 26600593<br>GDP(million): 700267",
"State: GA<br>Total Awarded Amount: 11216327<br>GDP(million): 388342",
"State: HI<br>Total Awarded Amount: 14427899<br>GDP(million): 58573",
"State: ID<br>Total Awarded Amount: 1961349<br>GDP(million): 47176",
"State: IL<br>Total Awarded Amount: 68112505<br>GDP(million): 586442",
"State: IN<br>Total Awarded Amount: 16377153<br>GDP(million): 245197",
"State: IA<br>Total Awarded Amount: 8493716<br>GDP(million): 123353",
"State: KS<br>Total Awarded Amount: 5764416<br>GDP(million): 104884",
"State: KY<br>Total Awarded Amount: 8022942<br>GDP(million): 143875",
"State: LA<br>Total Awarded Amount: 7978539<br>GDP(million): 199683",
"State: ME<br>Total Awarded Amount: 11177079<br>GDP(million): 46277",
"State: MD<br>Total Awarded Amount: 21671260<br>GDP(million): 263809",
"State: MA<br>Total Awarded Amount: 45976945<br>GDP(million): 345059",
"State: MI<br>Total Awarded Amount: 28799226<br>GDP(million): 395166",
"State: MN<br>Total Awarded Amount: 15325162<br>GDP(million): 243933",
"State: MS<br>Total Awarded Amount: 2787779<br>GDP(million): 81678",
"State: MO<br>Total Awarded Amount: 14911587<br>GDP(million): 224091",
"State: MT<br>Total Awarded Amount: 10424194<br>GDP(million): 30637",
"State: NE<br>Total Awarded Amount: 6600356<br>GDP(million): 73455",
"State: NV<br>Total Awarded Amount: 3677624<br>GDP(million): 118785",
"State: NH<br>Total Awarded Amount: 4797223<br>GDP(million): 57282",
"State: NJ<br>Total Awarded Amount: 11475362<br>GDP(million): 443148",
"State: NM<br>Total Awarded Amount: 10640574<br>GDP(million): 74403",
"State: NY<br>Total Awarded Amount: 105860170<br>GDP(million): 1023433",
"State: NC<br>Total Awarded Amount: 29992038<br>GDP(million): 357168",
"State: ND<br>Total Awarded Amount: 3071608<br>GDP(million): 24622",
"State: OH<br>Total Awarded Amount: 22015009<br>GDP(million): 467392",
"State: OK<br>Total Awarded Amount: 12405823<br>GDP(million): 125243",
"State: OR<br>Total Awarded Amount: 9556529<br>GDP(million): 147535",
"State: PA<br>Total Awarded Amount: 59575053<br>GDP(million): 506505",
"State: RI<br>Total Awarded Amount: 4751919<br>GDP(million): 45663",
"State: SC<br>Total Awarded Amount: 9063478<br>GDP(million): 143585",
"State: SD<br>Total Awarded Amount: 3596551<br>GDP(million): 31380",
"State: TN<br>Total Awarded Amount: 18083590<br>GDP(million): 227505",
"State: TX<br>Total Awarded Amount: 48252344<br>GDP(million): 990054",
"State: UT<br>Total Awarded Amount: 6884351<br>GDP(million): 94475",
"State: VT<br>Total Awarded Amount: 6381133<br>GDP(million): 23539",
"State: VA<br>Total Awarded Amount: 18068081<br>GDP(million): 359273",
"State: WA<br>Total Awarded Amount: 23476750<br>GDP(million): 296403",
"State: WV<br>Total Awarded Amount: 927680<br>GDP(million): 53453",
"State: WI<br>Total Awarded Amount: 17075827<br>GDP(million): 226325",
"State: WY<br>Total Awarded Amount: 2210361<br>GDP(million): 27454]"],
  "type": "scattergeo", 
  "uid": "782dcc"
}

In [67]:
trace9 = {
  "hoverinfo": "text", 
  "lat": [33.448, 29.954, 42.373611, 38.328732, 43.038902, 41.85, 39.768, 47.606, 33.792461, 39.29, 38.627, 44.979, 40.73061, 37.774, 37.339, 40.44, 34.052, 25.774, 29.763, 42.886], 
  "locationmode": "USA-states", 
  "lon": [-112.066667, -90.066667, -71.110556, -85.764771, -87.906471, -87.684722, -86.15, -122.333056, -118.185005, -76.616667, -90.197778, -93.266667, -73.935242, -122.416667, -121.9, -79.976389, -118.25, -80.208889, -95.383056, -78.849444], 
  "marker": {
    "color": "yellow", 
    "line": {
      "color": "orange", 
      "width": 1
    }, 
    "opacity": 0.1, 
    "size": [34.125, 28.875, 27.75, 27.75, 27.75, 27.5, 25, 14.75, 13.875, 13.125, 12.5, 12.5, 12.25, 12.25, 11.375, 11.375, 10.875, 9.625, 8.375, 7.75]
  }, 
  "showlegend": False, 
 "text": ["State: AL<br>Total Awarded Amount: 5743215<br>GDP(million):   156750",
"State: AK<br>Total Awarded Amount: 16189749<br>GDP(million): 40063",
"State: AZ<br>Total Awarded Amount: 19037687<br>GDP(million): 227358",
"State: AR<br>Total Awarded Amount: 1965330<br>GDP(million): 90319",
"State: CA<br>Total Awarded Amount: 74663752<br>GDP(million): 1766693",
"State: CO<br>Total Awarded Amount: 22235728<br>GDP(million): 220454",
"State: CT<br>Total Awarded Amount: 16501999<br>GDP(million): 210170",
"State: DE<br>Total Awarded Amount: 3857523<br>GDP(million): 53247",
"State: DC<br>Total Awarded Amount: 25424106<br>GDP(million): 83586",
"State: FL<br>Total Awarded Amount: 26600593<br>GDP(million): 700267",
"State: GA<br>Total Awarded Amount: 11216327<br>GDP(million): 388342",
"State: HI<br>Total Awarded Amount: 14427899<br>GDP(million): 58573",
"State: ID<br>Total Awarded Amount: 1961349<br>GDP(million): 47176",
"State: IL<br>Total Awarded Amount: 68112505<br>GDP(million): 586442",
"State: IN<br>Total Awarded Amount: 16377153<br>GDP(million): 245197",
"State: IA<br>Total Awarded Amount: 8493716<br>GDP(million): 123353",
"State: KS<br>Total Awarded Amount: 5764416<br>GDP(million): 104884",
"State: KY<br>Total Awarded Amount: 8022942<br>GDP(million): 143875",
"State: LA<br>Total Awarded Amount: 7978539<br>GDP(million): 199683",
"State: ME<br>Total Awarded Amount: 11177079<br>GDP(million): 46277",
"State: MD<br>Total Awarded Amount: 21671260<br>GDP(million): 263809",
"State: MA<br>Total Awarded Amount: 45976945<br>GDP(million): 345059",
"State: MI<br>Total Awarded Amount: 28799226<br>GDP(million): 395166",
"State: MN<br>Total Awarded Amount: 15325162<br>GDP(million): 243933",
"State: MS<br>Total Awarded Amount: 2787779<br>GDP(million): 81678",
"State: MO<br>Total Awarded Amount: 14911587<br>GDP(million): 224091",
"State: MT<br>Total Awarded Amount: 10424194<br>GDP(million): 30637",
"State: NE<br>Total Awarded Amount: 6600356<br>GDP(million): 73455",
"State: NV<br>Total Awarded Amount: 3677624<br>GDP(million): 118785",
"State: NH<br>Total Awarded Amount: 4797223<br>GDP(million): 57282",
"State: NJ<br>Total Awarded Amount: 11475362<br>GDP(million): 443148",
"State: NM<br>Total Awarded Amount: 10640574<br>GDP(million): 74403",
"State: NY<br>Total Awarded Amount: 105860170<br>GDP(million): 1023433",
"State: NC<br>Total Awarded Amount: 29992038<br>GDP(million): 357168",
"State: ND<br>Total Awarded Amount: 3071608<br>GDP(million): 24622",
"State: OH<br>Total Awarded Amount: 22015009<br>GDP(million): 467392",
"State: OK<br>Total Awarded Amount: 12405823<br>GDP(million): 125243",
"State: OR<br>Total Awarded Amount: 9556529<br>GDP(million): 147535",
"State: PA<br>Total Awarded Amount: 59575053<br>GDP(million): 506505",
"State: RI<br>Total Awarded Amount: 4751919<br>GDP(million): 45663",
"State: SC<br>Total Awarded Amount: 9063478<br>GDP(million): 143585",
"State: SD<br>Total Awarded Amount: 3596551<br>GDP(million): 31380",
"State: TN<br>Total Awarded Amount: 18083590<br>GDP(million): 227505",
"State: TX<br>Total Awarded Amount: 48252344<br>GDP(million): 990054",
"State: UT<br>Total Awarded Amount: 6884351<br>GDP(million): 94475",
"State: VT<br>Total Awarded Amount: 6381133<br>GDP(million): 23539",
"State: VA<br>Total Awarded Amount: 18068081<br>GDP(million): 359273",
"State: WA<br>Total Awarded Amount: 23476750<br>GDP(million): 296403",
"State: WV<br>Total Awarded Amount: 927680<br>GDP(million): 53453",
"State: WI<br>Total Awarded Amount: 17075827<br>GDP(million): 226325",
"State: WY<br>Total Awarded Amount: 2210361<br>GDP(million): 27454]"],
  "type": "scattergeo", 
  "uid": "31d5a2"
}

In [68]:
trace10 = {
  "hoverinfo": "text", 
  "lat": [33.448, 29.954, 42.373611, 38.328732, 43.038902, 41.85, 39.768, 47.606, 33.792461, 39.29, 38.627, 44.979, 40.73061, 37.774, 37.339, 40.44, 34.052, 25.774, 29.763, 42.886], 
  "locationmode": "USA-states", 
  "lon": [-112.066667, -90.066667, -71.110556, -85.764771, -87.906471, -87.684722, -86.15, -122.333056, -118.185005, -76.616667, -90.197778, -93.266667, -73.935242, -122.416667, -121.9, -79.976389, -118.25, -80.208889, -95.383056, -78.849444], 
  "marker": {
    "color": "yellow", 
    "line": {
      "color": "orange", 
      "width": 1
    }, 
    "opacity": 0.1, 
    "size": [34.125, 28.875, 27.75, 27.75, 27.75, 27.5, 25, 14.75, 13.875, 13.125, 12.5, 12.5, 12.25, 12.25, 11.375, 11.375, 10.875, 9.625, 8.375, 7.75]
  }, 
  "showlegend": False, 
 "text": ["State: AL<br>Total Awarded Amount: 5743215<br>GDP(million):   156750",
"State: AK<br>Total Awarded Amount: 16189749<br>GDP(million): 40063",
"State: AZ<br>Total Awarded Amount: 19037687<br>GDP(million): 227358",
"State: AR<br>Total Awarded Amount: 1965330<br>GDP(million): 90319",
"State: CA<br>Total Awarded Amount: 74663752<br>GDP(million): 1766693",
"State: CO<br>Total Awarded Amount: 22235728<br>GDP(million): 220454",
"State: CT<br>Total Awarded Amount: 16501999<br>GDP(million): 210170",
"State: DE<br>Total Awarded Amount: 3857523<br>GDP(million): 53247",
"State: DC<br>Total Awarded Amount: 25424106<br>GDP(million): 83586",
"State: FL<br>Total Awarded Amount: 26600593<br>GDP(million): 700267",
"State: GA<br>Total Awarded Amount: 11216327<br>GDP(million): 388342",
"State: HI<br>Total Awarded Amount: 14427899<br>GDP(million): 58573",
"State: ID<br>Total Awarded Amount: 1961349<br>GDP(million): 47176",
"State: IL<br>Total Awarded Amount: 68112505<br>GDP(million): 586442",
"State: IN<br>Total Awarded Amount: 16377153<br>GDP(million): 245197",
"State: IA<br>Total Awarded Amount: 8493716<br>GDP(million): 123353",
"State: KS<br>Total Awarded Amount: 5764416<br>GDP(million): 104884",
"State: KY<br>Total Awarded Amount: 8022942<br>GDP(million): 143875",
"State: LA<br>Total Awarded Amount: 7978539<br>GDP(million): 199683",
"State: ME<br>Total Awarded Amount: 11177079<br>GDP(million): 46277",
"State: MD<br>Total Awarded Amount: 21671260<br>GDP(million): 263809",
"State: MA<br>Total Awarded Amount: 45976945<br>GDP(million): 345059",
"State: MI<br>Total Awarded Amount: 28799226<br>GDP(million): 395166",
"State: MN<br>Total Awarded Amount: 15325162<br>GDP(million): 243933",
"State: MS<br>Total Awarded Amount: 2787779<br>GDP(million): 81678",
"State: MO<br>Total Awarded Amount: 14911587<br>GDP(million): 224091",
"State: MT<br>Total Awarded Amount: 10424194<br>GDP(million): 30637",
"State: NE<br>Total Awarded Amount: 6600356<br>GDP(million): 73455",
"State: NV<br>Total Awarded Amount: 3677624<br>GDP(million): 118785",
"State: NH<br>Total Awarded Amount: 4797223<br>GDP(million): 57282",
"State: NJ<br>Total Awarded Amount: 11475362<br>GDP(million): 443148",
"State: NM<br>Total Awarded Amount: 10640574<br>GDP(million): 74403",
"State: NY<br>Total Awarded Amount: 105860170<br>GDP(million): 1023433",
"State: NC<br>Total Awarded Amount: 29992038<br>GDP(million): 357168",
"State: ND<br>Total Awarded Amount: 3071608<br>GDP(million): 24622",
"State: OH<br>Total Awarded Amount: 22015009<br>GDP(million): 467392",
"State: OK<br>Total Awarded Amount: 12405823<br>GDP(million): 125243",
"State: OR<br>Total Awarded Amount: 9556529<br>GDP(million): 147535",
"State: PA<br>Total Awarded Amount: 59575053<br>GDP(million): 506505",
"State: RI<br>Total Awarded Amount: 4751919<br>GDP(million): 45663",
"State: SC<br>Total Awarded Amount: 9063478<br>GDP(million): 143585",
"State: SD<br>Total Awarded Amount: 3596551<br>GDP(million): 31380",
"State: TN<br>Total Awarded Amount: 18083590<br>GDP(million): 227505",
"State: TX<br>Total Awarded Amount: 48252344<br>GDP(million): 990054",
"State: UT<br>Total Awarded Amount: 6884351<br>GDP(million): 94475",
"State: VT<br>Total Awarded Amount: 6381133<br>GDP(million): 23539",
"State: VA<br>Total Awarded Amount: 18068081<br>GDP(million): 359273",
"State: WA<br>Total Awarded Amount: 23476750<br>GDP(million): 296403",
"State: WV<br>Total Awarded Amount: 927680<br>GDP(million): 53453",
"State: WI<br>Total Awarded Amount: 17075827<br>GDP(million): 226325",
"State: WY<br>Total Awarded Amount: 2210361<br>GDP(million): 27454]"],
  "type": "scattergeo", 
  "uid": "a66259"
}
trace11 = {
  "hoverinfo": "text", 
  "lat": [33.448, 29.954, 42.373611, 38.328732, 43.038902, 41.85, 39.768, 47.606, 33.792461, 39.29, 38.627, 44.979, 40.73061, 37.774, 37.339, 40.44, 34.052, 25.774, 29.763, 42.886], 
  "locationmode": "USA-states", 
  "lon": [-112.066667, -90.066667, -71.110556, -85.764771, -87.906471, -87.684722, -86.15, -122.333056, -118.185005, -76.616667, -90.197778, -93.266667, -73.935242, -122.416667, -121.9, -79.976389, -118.25, -80.208889, -95.383056, -78.849444], 
  "marker": {
    "color": "yellow", 
    "line": {
      "color": "orange", 
      "width": 1
    }, 
    "opacity": 0.1, 
    "size": [34.125, 28.875, 27.75, 27.75, 27.75, 27.5, 25, 14.75, 13.875, 13.125, 12.5, 12.5, 12.25, 12.25, 11.375, 11.375, 10.875, 9.625, 8.375, 7.75]
  }, 
  "showlegend": False, 
 "text": ["State: AL<br>Total Awarded Amount: 5743215<br>GDP(million):   156750",
"State: AK<br>Total Awarded Amount: 16189749<br>GDP(million): 40063",
"State: AZ<br>Total Awarded Amount: 19037687<br>GDP(million): 227358",
"State: AR<br>Total Awarded Amount: 1965330<br>GDP(million): 90319",
"State: CA<br>Total Awarded Amount: 74663752<br>GDP(million): 1766693",
"State: CO<br>Total Awarded Amount: 22235728<br>GDP(million): 220454",
"State: CT<br>Total Awarded Amount: 16501999<br>GDP(million): 210170",
"State: DE<br>Total Awarded Amount: 3857523<br>GDP(million): 53247",
"State: DC<br>Total Awarded Amount: 25424106<br>GDP(million): 83586",
"State: FL<br>Total Awarded Amount: 26600593<br>GDP(million): 700267",
"State: GA<br>Total Awarded Amount: 11216327<br>GDP(million): 388342",
"State: HI<br>Total Awarded Amount: 14427899<br>GDP(million): 58573",
"State: ID<br>Total Awarded Amount: 1961349<br>GDP(million): 47176",
"State: IL<br>Total Awarded Amount: 68112505<br>GDP(million): 586442",
"State: IN<br>Total Awarded Amount: 16377153<br>GDP(million): 245197",
"State: IA<br>Total Awarded Amount: 8493716<br>GDP(million): 123353",
"State: KS<br>Total Awarded Amount: 5764416<br>GDP(million): 104884",
"State: KY<br>Total Awarded Amount: 8022942<br>GDP(million): 143875",
"State: LA<br>Total Awarded Amount: 7978539<br>GDP(million): 199683",
"State: ME<br>Total Awarded Amount: 11177079<br>GDP(million): 46277",
"State: MD<br>Total Awarded Amount: 21671260<br>GDP(million): 263809",
"State: MA<br>Total Awarded Amount: 45976945<br>GDP(million): 345059",
"State: MI<br>Total Awarded Amount: 28799226<br>GDP(million): 395166",
"State: MN<br>Total Awarded Amount: 15325162<br>GDP(million): 243933",
"State: MS<br>Total Awarded Amount: 2787779<br>GDP(million): 81678",
"State: MO<br>Total Awarded Amount: 14911587<br>GDP(million): 224091",
"State: MT<br>Total Awarded Amount: 10424194<br>GDP(million): 30637",
"State: NE<br>Total Awarded Amount: 6600356<br>GDP(million): 73455",
"State: NV<br>Total Awarded Amount: 3677624<br>GDP(million): 118785",
"State: NH<br>Total Awarded Amount: 4797223<br>GDP(million): 57282",
"State: NJ<br>Total Awarded Amount: 11475362<br>GDP(million): 443148",
"State: NM<br>Total Awarded Amount: 10640574<br>GDP(million): 74403",
"State: NY<br>Total Awarded Amount: 105860170<br>GDP(million): 1023433",
"State: NC<br>Total Awarded Amount: 29992038<br>GDP(million): 357168",
"State: ND<br>Total Awarded Amount: 3071608<br>GDP(million): 24622",
"State: OH<br>Total Awarded Amount: 22015009<br>GDP(million): 467392",
"State: OK<br>Total Awarded Amount: 12405823<br>GDP(million): 125243",
"State: OR<br>Total Awarded Amount: 9556529<br>GDP(million): 147535",
"State: PA<br>Total Awarded Amount: 59575053<br>GDP(million): 506505",
"State: RI<br>Total Awarded Amount: 4751919<br>GDP(million): 45663",
"State: SC<br>Total Awarded Amount: 9063478<br>GDP(million): 143585",
"State: SD<br>Total Awarded Amount: 3596551<br>GDP(million): 31380",
"State: TN<br>Total Awarded Amount: 18083590<br>GDP(million): 227505",
"State: TX<br>Total Awarded Amount: 48252344<br>GDP(million): 990054",
"State: UT<br>Total Awarded Amount: 6884351<br>GDP(million): 94475",
"State: VT<br>Total Awarded Amount: 6381133<br>GDP(million): 23539",
"State: VA<br>Total Awarded Amount: 18068081<br>GDP(million): 359273",
"State: WA<br>Total Awarded Amount: 23476750<br>GDP(million): 296403",
"State: WV<br>Total Awarded Amount: 927680<br>GDP(million): 53453",
"State: WI<br>Total Awarded Amount: 17075827<br>GDP(million): 226325",
"State: WY<br>Total Awarded Amount: 2210361<br>GDP(million): 27454]"],
  "type": "scattergeo", 
  "uid": "55adf3"
}
trace12 = {
  "hoverinfo": "text", 
  "lat": [33.448, 29.954, 42.373611, 38.328732, 43.038902, 41.85, 39.768, 47.606, 33.792461, 39.29, 38.627, 44.979, 40.73061, 37.774, 37.339, 40.44, 34.052, 25.774, 29.763, 42.886], 
  "locationmode": "USA-states", 
  "lon": [-112.066667, -90.066667, -71.110556, -85.764771, -87.906471, -87.684722, -86.15, -122.333056, -118.185005, -76.616667, -90.197778, -93.266667, -73.935242, -122.416667, -121.9, -79.976389, -118.25, -80.208889, -95.383056, -78.849444], 
  "marker": {
    "color": "yellow", 
    "line": {
      "color": "orange", 
      "width": 1
    }, 
    "opacity": 0.1, 
    "size": [34.125, 28.875, 27.75, 27.75, 27.75, 27.5, 25, 14.75, 13.875, 13.125, 12.5, 12.5, 12.25, 12.25, 11.375, 11.375, 10.875, 9.625, 8.375, 7.75]
  }, 
  "showlegend": False, 
 "text": ["State: AL<br>Total Awarded Amount: 5743215<br>GDP(million):   156750",
"State: AK<br>Total Awarded Amount: 16189749<br>GDP(million): 40063",
"State: AZ<br>Total Awarded Amount: 19037687<br>GDP(million): 227358",
"State: AR<br>Total Awarded Amount: 1965330<br>GDP(million): 90319",
"State: CA<br>Total Awarded Amount: 74663752<br>GDP(million): 1766693",
"State: CO<br>Total Awarded Amount: 22235728<br>GDP(million): 220454",
"State: CT<br>Total Awarded Amount: 16501999<br>GDP(million): 210170",
"State: DE<br>Total Awarded Amount: 3857523<br>GDP(million): 53247",
"State: DC<br>Total Awarded Amount: 25424106<br>GDP(million): 83586",
"State: FL<br>Total Awarded Amount: 26600593<br>GDP(million): 700267",
"State: GA<br>Total Awarded Amount: 11216327<br>GDP(million): 388342",
"State: HI<br>Total Awarded Amount: 14427899<br>GDP(million): 58573",
"State: ID<br>Total Awarded Amount: 1961349<br>GDP(million): 47176",
"State: IL<br>Total Awarded Amount: 68112505<br>GDP(million): 586442",
"State: IN<br>Total Awarded Amount: 16377153<br>GDP(million): 245197",
"State: IA<br>Total Awarded Amount: 8493716<br>GDP(million): 123353",
"State: KS<br>Total Awarded Amount: 5764416<br>GDP(million): 104884",
"State: KY<br>Total Awarded Amount: 8022942<br>GDP(million): 143875",
"State: LA<br>Total Awarded Amount: 7978539<br>GDP(million): 199683",
"State: ME<br>Total Awarded Amount: 11177079<br>GDP(million): 46277",
"State: MD<br>Total Awarded Amount: 21671260<br>GDP(million): 263809",
"State: MA<br>Total Awarded Amount: 45976945<br>GDP(million): 345059",
"State: MI<br>Total Awarded Amount: 28799226<br>GDP(million): 395166",
"State: MN<br>Total Awarded Amount: 15325162<br>GDP(million): 243933",
"State: MS<br>Total Awarded Amount: 2787779<br>GDP(million): 81678",
"State: MO<br>Total Awarded Amount: 14911587<br>GDP(million): 224091",
"State: MT<br>Total Awarded Amount: 10424194<br>GDP(million): 30637",
"State: NE<br>Total Awarded Amount: 6600356<br>GDP(million): 73455",
"State: NV<br>Total Awarded Amount: 3677624<br>GDP(million): 118785",
"State: NH<br>Total Awarded Amount: 4797223<br>GDP(million): 57282",
"State: NJ<br>Total Awarded Amount: 11475362<br>GDP(million): 443148",
"State: NM<br>Total Awarded Amount: 10640574<br>GDP(million): 74403",
"State: NY<br>Total Awarded Amount: 105860170<br>GDP(million): 1023433",
"State: NC<br>Total Awarded Amount: 29992038<br>GDP(million): 357168",
"State: ND<br>Total Awarded Amount: 3071608<br>GDP(million): 24622",
"State: OH<br>Total Awarded Amount: 22015009<br>GDP(million): 467392",
"State: OK<br>Total Awarded Amount: 12405823<br>GDP(million): 125243",
"State: OR<br>Total Awarded Amount: 9556529<br>GDP(million): 147535",
"State: PA<br>Total Awarded Amount: 59575053<br>GDP(million): 506505",
"State: RI<br>Total Awarded Amount: 4751919<br>GDP(million): 45663",
"State: SC<br>Total Awarded Amount: 9063478<br>GDP(million): 143585",
"State: SD<br>Total Awarded Amount: 3596551<br>GDP(million): 31380",
"State: TN<br>Total Awarded Amount: 18083590<br>GDP(million): 227505",
"State: TX<br>Total Awarded Amount: 48252344<br>GDP(million): 990054",
"State: UT<br>Total Awarded Amount: 6884351<br>GDP(million): 94475",
"State: VT<br>Total Awarded Amount: 6381133<br>GDP(million): 23539",
"State: VA<br>Total Awarded Amount: 18068081<br>GDP(million): 359273",
"State: WA<br>Total Awarded Amount: 23476750<br>GDP(million): 296403",
"State: WV<br>Total Awarded Amount: 927680<br>GDP(million): 53453",
"State: WI<br>Total Awarded Amount: 17075827<br>GDP(million): 226325",
"State: WY<br>Total Awarded Amount: 2210361<br>GDP(million): 27454]"],
  "type": "scattergeo", 
  "uid": "7488d1"
}
trace13 = {
  "hoverinfo": "text", 
  "lat": [33.448, 29.954, 42.373611, 38.328732, 43.038902, 41.85, 39.768, 47.606, 33.792461, 39.29, 38.627, 44.979, 40.73061, 37.774, 37.339, 40.44, 34.052, 25.774, 29.763, 42.886], 
  "locationmode": "USA-states", 
  "lon": [-112.066667, -90.066667, -71.110556, -85.764771, -87.906471, -87.684722, -86.15, -122.333056, -118.185005, -76.616667, -90.197778, -93.266667, -73.935242, -122.416667, -121.9, -79.976389, -118.25, -80.208889, -95.383056, -78.849444], 
  "marker": {
    "color": "yellow", 
    "line": {
      "color": "orange", 
      "width": 1
    }, 
    "opacity": 0.1, 
    "size": [34.125, 28.875, 27.75, 27.75, 27.75, 27.5, 25, 14.75, 13.875, 13.125, 12.5, 12.5, 12.25, 12.25, 11.375, 11.375, 10.875, 9.625, 8.375, 7.75]
  }, 
  "showlegend": False, 
 "text": ["State: AL<br>Total Awarded Amount: 5743215<br>GDP(million):   156750",
"State: AK<br>Total Awarded Amount: 16189749<br>GDP(million): 40063",
"State: AZ<br>Total Awarded Amount: 19037687<br>GDP(million): 227358",
"State: AR<br>Total Awarded Amount: 1965330<br>GDP(million): 90319",
"State: CA<br>Total Awarded Amount: 74663752<br>GDP(million): 1766693",
"State: CO<br>Total Awarded Amount: 22235728<br>GDP(million): 220454",
"State: CT<br>Total Awarded Amount: 16501999<br>GDP(million): 210170",
"State: DE<br>Total Awarded Amount: 3857523<br>GDP(million): 53247",
"State: DC<br>Total Awarded Amount: 25424106<br>GDP(million): 83586",
"State: FL<br>Total Awarded Amount: 26600593<br>GDP(million): 700267",
"State: GA<br>Total Awarded Amount: 11216327<br>GDP(million): 388342",
"State: HI<br>Total Awarded Amount: 14427899<br>GDP(million): 58573",
"State: ID<br>Total Awarded Amount: 1961349<br>GDP(million): 47176",
"State: IL<br>Total Awarded Amount: 68112505<br>GDP(million): 586442",
"State: IN<br>Total Awarded Amount: 16377153<br>GDP(million): 245197",
"State: IA<br>Total Awarded Amount: 8493716<br>GDP(million): 123353",
"State: KS<br>Total Awarded Amount: 5764416<br>GDP(million): 104884",
"State: KY<br>Total Awarded Amount: 8022942<br>GDP(million): 143875",
"State: LA<br>Total Awarded Amount: 7978539<br>GDP(million): 199683",
"State: ME<br>Total Awarded Amount: 11177079<br>GDP(million): 46277",
"State: MD<br>Total Awarded Amount: 21671260<br>GDP(million): 263809",
"State: MA<br>Total Awarded Amount: 45976945<br>GDP(million): 345059",
"State: MI<br>Total Awarded Amount: 28799226<br>GDP(million): 395166",
"State: MN<br>Total Awarded Amount: 15325162<br>GDP(million): 243933",
"State: MS<br>Total Awarded Amount: 2787779<br>GDP(million): 81678",
"State: MO<br>Total Awarded Amount: 14911587<br>GDP(million): 224091",
"State: MT<br>Total Awarded Amount: 10424194<br>GDP(million): 30637",
"State: NE<br>Total Awarded Amount: 6600356<br>GDP(million): 73455",
"State: NV<br>Total Awarded Amount: 3677624<br>GDP(million): 118785",
"State: NH<br>Total Awarded Amount: 4797223<br>GDP(million): 57282",
"State: NJ<br>Total Awarded Amount: 11475362<br>GDP(million): 443148",
"State: NM<br>Total Awarded Amount: 10640574<br>GDP(million): 74403",
"State: NY<br>Total Awarded Amount: 105860170<br>GDP(million): 1023433",
"State: NC<br>Total Awarded Amount: 29992038<br>GDP(million): 357168",
"State: ND<br>Total Awarded Amount: 3071608<br>GDP(million): 24622",
"State: OH<br>Total Awarded Amount: 22015009<br>GDP(million): 467392",
"State: OK<br>Total Awarded Amount: 12405823<br>GDP(million): 125243",
"State: OR<br>Total Awarded Amount: 9556529<br>GDP(million): 147535",
"State: PA<br>Total Awarded Amount: 59575053<br>GDP(million): 506505",
"State: RI<br>Total Awarded Amount: 4751919<br>GDP(million): 45663",
"State: SC<br>Total Awarded Amount: 9063478<br>GDP(million): 143585",
"State: SD<br>Total Awarded Amount: 3596551<br>GDP(million): 31380",
"State: TN<br>Total Awarded Amount: 18083590<br>GDP(million): 227505",
"State: TX<br>Total Awarded Amount: 48252344<br>GDP(million): 990054",
"State: UT<br>Total Awarded Amount: 6884351<br>GDP(million): 94475",
"State: VT<br>Total Awarded Amount: 6381133<br>GDP(million): 23539",
"State: VA<br>Total Awarded Amount: 18068081<br>GDP(million): 359273",
"State: WA<br>Total Awarded Amount: 23476750<br>GDP(million): 296403",
"State: WV<br>Total Awarded Amount: 927680<br>GDP(million): 53453",
"State: WI<br>Total Awarded Amount: 17075827<br>GDP(million): 226325",
"State: WY<br>Total Awarded Amount: 2210361<br>GDP(million): 27454]"],
  "type": "scattergeo", 
  "uid": "d51f63"
}
trace14 = {
  "hoverinfo": "text", 
  "lat": [33.448, 29.954, 42.373611, 38.328732, 43.038902, 41.85, 39.768, 47.606, 33.792461, 39.29, 38.627, 44.979, 40.73061, 37.774, 37.339, 40.44, 34.052, 25.774, 29.763, 42.886], 
  "locationmode": "USA-states", 
  "lon": [-112.066667, -90.066667, -71.110556, -85.764771, -87.906471, -87.684722, -86.15, -122.333056, -118.185005, -76.616667, -90.197778, -93.266667, -73.935242, -122.416667, -121.9, -79.976389, -118.25, -80.208889, -95.383056, -78.849444], 
  "marker": {
    "color": "yellow", 
    "line": {
      "color": "orange", 
      "width": 1
    }, 
    "opacity": 0.1, 
    "size": [34.125, 28.875, 27.75, 27.75, 27.75, 27.5, 25, 14.75, 13.875, 13.125, 12.5, 12.5, 12.25, 12.25, 11.375, 11.375, 10.875, 9.625, 8.375, 7.75]
  }, 
  "showlegend": False, 
 "text": ["State: AL<br>Total Awarded Amount: 5743215<br>GDP(million):   156750",
"State: AK<br>Total Awarded Amount: 16189749<br>GDP(million): 40063",
"State: AZ<br>Total Awarded Amount: 19037687<br>GDP(million): 227358",
"State: AR<br>Total Awarded Amount: 1965330<br>GDP(million): 90319",
"State: CA<br>Total Awarded Amount: 74663752<br>GDP(million): 1766693",
"State: CO<br>Total Awarded Amount: 22235728<br>GDP(million): 220454",
"State: CT<br>Total Awarded Amount: 16501999<br>GDP(million): 210170",
"State: DE<br>Total Awarded Amount: 3857523<br>GDP(million): 53247",
"State: DC<br>Total Awarded Amount: 25424106<br>GDP(million): 83586",
"State: FL<br>Total Awarded Amount: 26600593<br>GDP(million): 700267",
"State: GA<br>Total Awarded Amount: 11216327<br>GDP(million): 388342",
"State: HI<br>Total Awarded Amount: 14427899<br>GDP(million): 58573",
"State: ID<br>Total Awarded Amount: 1961349<br>GDP(million): 47176",
"State: IL<br>Total Awarded Amount: 68112505<br>GDP(million): 586442",
"State: IN<br>Total Awarded Amount: 16377153<br>GDP(million): 245197",
"State: IA<br>Total Awarded Amount: 8493716<br>GDP(million): 123353",
"State: KS<br>Total Awarded Amount: 5764416<br>GDP(million): 104884",
"State: KY<br>Total Awarded Amount: 8022942<br>GDP(million): 143875",
"State: LA<br>Total Awarded Amount: 7978539<br>GDP(million): 199683",
"State: ME<br>Total Awarded Amount: 11177079<br>GDP(million): 46277",
"State: MD<br>Total Awarded Amount: 21671260<br>GDP(million): 263809",
"State: MA<br>Total Awarded Amount: 45976945<br>GDP(million): 345059",
"State: MI<br>Total Awarded Amount: 28799226<br>GDP(million): 395166",
"State: MN<br>Total Awarded Amount: 15325162<br>GDP(million): 243933",
"State: MS<br>Total Awarded Amount: 2787779<br>GDP(million): 81678",
"State: MO<br>Total Awarded Amount: 14911587<br>GDP(million): 224091",
"State: MT<br>Total Awarded Amount: 10424194<br>GDP(million): 30637",
"State: NE<br>Total Awarded Amount: 6600356<br>GDP(million): 73455",
"State: NV<br>Total Awarded Amount: 3677624<br>GDP(million): 118785",
"State: NH<br>Total Awarded Amount: 4797223<br>GDP(million): 57282",
"State: NJ<br>Total Awarded Amount: 11475362<br>GDP(million): 443148",
"State: NM<br>Total Awarded Amount: 10640574<br>GDP(million): 74403",
"State: NY<br>Total Awarded Amount: 105860170<br>GDP(million): 1023433",
"State: NC<br>Total Awarded Amount: 29992038<br>GDP(million): 357168",
"State: ND<br>Total Awarded Amount: 3071608<br>GDP(million): 24622",
"State: OH<br>Total Awarded Amount: 22015009<br>GDP(million): 467392",
"State: OK<br>Total Awarded Amount: 12405823<br>GDP(million): 125243",
"State: OR<br>Total Awarded Amount: 9556529<br>GDP(million): 147535",
"State: PA<br>Total Awarded Amount: 59575053<br>GDP(million): 506505",
"State: RI<br>Total Awarded Amount: 4751919<br>GDP(million): 45663",
"State: SC<br>Total Awarded Amount: 9063478<br>GDP(million): 143585",
"State: SD<br>Total Awarded Amount: 3596551<br>GDP(million): 31380",
"State: TN<br>Total Awarded Amount: 18083590<br>GDP(million): 227505",
"State: TX<br>Total Awarded Amount: 48252344<br>GDP(million): 990054",
"State: UT<br>Total Awarded Amount: 6884351<br>GDP(million): 94475",
"State: VT<br>Total Awarded Amount: 6381133<br>GDP(million): 23539",
"State: VA<br>Total Awarded Amount: 18068081<br>GDP(million): 359273",
"State: WA<br>Total Awarded Amount: 23476750<br>GDP(million): 296403",
"State: WV<br>Total Awarded Amount: 927680<br>GDP(million): 53453",
"State: WI<br>Total Awarded Amount: 17075827<br>GDP(million): 226325",
"State: WY<br>Total Awarded Amount: 2210361<br>GDP(million): 27454]"],
  "type": "scattergeo", 
  "uid": "64c7bd"
}
trace15 = {
  "hoverinfo": "text", 
  "lat": [33.448, 29.954, 42.373611, 38.328732, 43.038902, 41.85, 39.768, 47.606, 33.792461, 39.29, 38.627, 44.979, 40.73061, 37.774, 37.339, 40.44, 34.052, 25.774, 29.763, 42.886], 
  "locationmode": "USA-states", 
  "lon": [-112.066667, -90.066667, -71.110556, -85.764771, -87.906471, -87.684722, -86.15, -122.333056, -118.185005, -76.616667, -90.197778, -93.266667, -73.935242, -122.416667, -121.9, -79.976389, -118.25, -80.208889, -95.383056, -78.849444], 
  "marker": {
    "color": "yellow", 
    "line": {
      "color": "orange", 
      "width": 1
    }, 
    "opacity": 0.1, 
    "size": [34.125, 28.875, 27.75, 27.75, 27.75, 27.5, 25, 14.75, 13.875, 13.125, 12.5, 12.5, 12.25, 12.25, 11.375, 11.375, 10.875, 9.625, 8.375, 7.75]
  }, 
  "showlegend": False, 
 "text": ["State: AL<br>Total Awarded Amount: 5743215<br>GDP(million):   156750",
"State: AK<br>Total Awarded Amount: 16189749<br>GDP(million): 40063",
"State: AZ<br>Total Awarded Amount: 19037687<br>GDP(million): 227358",
"State: AR<br>Total Awarded Amount: 1965330<br>GDP(million): 90319",
"State: CA<br>Total Awarded Amount: 74663752<br>GDP(million): 1766693",
"State: CO<br>Total Awarded Amount: 22235728<br>GDP(million): 220454",
"State: CT<br>Total Awarded Amount: 16501999<br>GDP(million): 210170",
"State: DE<br>Total Awarded Amount: 3857523<br>GDP(million): 53247",
"State: DC<br>Total Awarded Amount: 25424106<br>GDP(million): 83586",
"State: FL<br>Total Awarded Amount: 26600593<br>GDP(million): 700267",
"State: GA<br>Total Awarded Amount: 11216327<br>GDP(million): 388342",
"State: HI<br>Total Awarded Amount: 14427899<br>GDP(million): 58573",
"State: ID<br>Total Awarded Amount: 1961349<br>GDP(million): 47176",
"State: IL<br>Total Awarded Amount: 68112505<br>GDP(million): 586442",
"State: IN<br>Total Awarded Amount: 16377153<br>GDP(million): 245197",
"State: IA<br>Total Awarded Amount: 8493716<br>GDP(million): 123353",
"State: KS<br>Total Awarded Amount: 5764416<br>GDP(million): 104884",
"State: KY<br>Total Awarded Amount: 8022942<br>GDP(million): 143875",
"State: LA<br>Total Awarded Amount: 7978539<br>GDP(million): 199683",
"State: ME<br>Total Awarded Amount: 11177079<br>GDP(million): 46277",
"State: MD<br>Total Awarded Amount: 21671260<br>GDP(million): 263809",
"State: MA<br>Total Awarded Amount: 45976945<br>GDP(million): 345059",
"State: MI<br>Total Awarded Amount: 28799226<br>GDP(million): 395166",
"State: MN<br>Total Awarded Amount: 15325162<br>GDP(million): 243933",
"State: MS<br>Total Awarded Amount: 2787779<br>GDP(million): 81678",
"State: MO<br>Total Awarded Amount: 14911587<br>GDP(million): 224091",
"State: MT<br>Total Awarded Amount: 10424194<br>GDP(million): 30637",
"State: NE<br>Total Awarded Amount: 6600356<br>GDP(million): 73455",
"State: NV<br>Total Awarded Amount: 3677624<br>GDP(million): 118785",
"State: NH<br>Total Awarded Amount: 4797223<br>GDP(million): 57282",
"State: NJ<br>Total Awarded Amount: 11475362<br>GDP(million): 443148",
"State: NM<br>Total Awarded Amount: 10640574<br>GDP(million): 74403",
"State: NY<br>Total Awarded Amount: 105860170<br>GDP(million): 1023433",
"State: NC<br>Total Awarded Amount: 29992038<br>GDP(million): 357168",
"State: ND<br>Total Awarded Amount: 3071608<br>GDP(million): 24622",
"State: OH<br>Total Awarded Amount: 22015009<br>GDP(million): 467392",
"State: OK<br>Total Awarded Amount: 12405823<br>GDP(million): 125243",
"State: OR<br>Total Awarded Amount: 9556529<br>GDP(million): 147535",
"State: PA<br>Total Awarded Amount: 59575053<br>GDP(million): 506505",
"State: RI<br>Total Awarded Amount: 4751919<br>GDP(million): 45663",
"State: SC<br>Total Awarded Amount: 9063478<br>GDP(million): 143585",
"State: SD<br>Total Awarded Amount: 3596551<br>GDP(million): 31380",
"State: TN<br>Total Awarded Amount: 18083590<br>GDP(million): 227505",
"State: TX<br>Total Awarded Amount: 48252344<br>GDP(million): 990054",
"State: UT<br>Total Awarded Amount: 6884351<br>GDP(million): 94475",
"State: VT<br>Total Awarded Amount: 6381133<br>GDP(million): 23539",
"State: VA<br>Total Awarded Amount: 18068081<br>GDP(million): 359273",
"State: WA<br>Total Awarded Amount: 23476750<br>GDP(million): 296403",
"State: WV<br>Total Awarded Amount: 927680<br>GDP(million): 53453",
"State: WI<br>Total Awarded Amount: 17075827<br>GDP(million): 226325",
"State: WY<br>Total Awarded Amount: 2210361<br>GDP(million): 27454]"],
  "type": "scattergeo", 
  "uid": "bf9c2b"
}
trace16 = {
  "hoverinfo": "text", 
  "lat": [33.448, 29.954, 42.373611, 38.328732, 43.038902, 41.85, 39.768, 47.606, 33.792461, 39.29, 38.627, 44.979, 40.73061, 37.774, 37.339, 40.44, 34.052, 25.774, 29.763, 42.886], 
  "locationmode": "USA-states", 
  "lon": [-112.066667, -90.066667, -71.110556, -85.764771, -87.906471, -87.684722, -86.15, -122.333056, -118.185005, -76.616667, -90.197778, -93.266667, -73.935242, -122.416667, -121.9, -79.976389, -118.25, -80.208889, -95.383056, -78.849444], 
  "marker": {
    "color": "yellow", 
    "line": {
      "color": "orange", 
      "width": 1
    }, 
    "opacity": 0.1, 
    "size": [34.125, 28.875, 27.75, 27.75, 27.75, 27.5, 25, 14.75, 13.875, 13.125, 12.5, 12.5, 12.25, 12.25, 11.375, 11.375, 10.875, 9.625, 8.375, 7.75]
  }, 
  "showlegend": False, 
 "text": ["State: AL<br>Total Awarded Amount: 5743215<br>GDP(million):   156750",
"State: AK<br>Total Awarded Amount: 16189749<br>GDP(million): 40063",
"State: AZ<br>Total Awarded Amount: 19037687<br>GDP(million): 227358",
"State: AR<br>Total Awarded Amount: 1965330<br>GDP(million): 90319",
"State: CA<br>Total Awarded Amount: 74663752<br>GDP(million): 1766693",
"State: CO<br>Total Awarded Amount: 22235728<br>GDP(million): 220454",
"State: CT<br>Total Awarded Amount: 16501999<br>GDP(million): 210170",
"State: DE<br>Total Awarded Amount: 3857523<br>GDP(million): 53247",
"State: DC<br>Total Awarded Amount: 25424106<br>GDP(million): 83586",
"State: FL<br>Total Awarded Amount: 26600593<br>GDP(million): 700267",
"State: GA<br>Total Awarded Amount: 11216327<br>GDP(million): 388342",
"State: HI<br>Total Awarded Amount: 14427899<br>GDP(million): 58573",
"State: ID<br>Total Awarded Amount: 1961349<br>GDP(million): 47176",
"State: IL<br>Total Awarded Amount: 68112505<br>GDP(million): 586442",
"State: IN<br>Total Awarded Amount: 16377153<br>GDP(million): 245197",
"State: IA<br>Total Awarded Amount: 8493716<br>GDP(million): 123353",
"State: KS<br>Total Awarded Amount: 5764416<br>GDP(million): 104884",
"State: KY<br>Total Awarded Amount: 8022942<br>GDP(million): 143875",
"State: LA<br>Total Awarded Amount: 7978539<br>GDP(million): 199683",
"State: ME<br>Total Awarded Amount: 11177079<br>GDP(million): 46277",
"State: MD<br>Total Awarded Amount: 21671260<br>GDP(million): 263809",
"State: MA<br>Total Awarded Amount: 45976945<br>GDP(million): 345059",
"State: MI<br>Total Awarded Amount: 28799226<br>GDP(million): 395166",
"State: MN<br>Total Awarded Amount: 15325162<br>GDP(million): 243933",
"State: MS<br>Total Awarded Amount: 2787779<br>GDP(million): 81678",
"State: MO<br>Total Awarded Amount: 14911587<br>GDP(million): 224091",
"State: MT<br>Total Awarded Amount: 10424194<br>GDP(million): 30637",
"State: NE<br>Total Awarded Amount: 6600356<br>GDP(million): 73455",
"State: NV<br>Total Awarded Amount: 3677624<br>GDP(million): 118785",
"State: NH<br>Total Awarded Amount: 4797223<br>GDP(million): 57282",
"State: NJ<br>Total Awarded Amount: 11475362<br>GDP(million): 443148",
"State: NM<br>Total Awarded Amount: 10640574<br>GDP(million): 74403",
"State: NY<br>Total Awarded Amount: 105860170<br>GDP(million): 1023433",
"State: NC<br>Total Awarded Amount: 29992038<br>GDP(million): 357168",
"State: ND<br>Total Awarded Amount: 3071608<br>GDP(million): 24622",
"State: OH<br>Total Awarded Amount: 22015009<br>GDP(million): 467392",
"State: OK<br>Total Awarded Amount: 12405823<br>GDP(million): 125243",
"State: OR<br>Total Awarded Amount: 9556529<br>GDP(million): 147535",
"State: PA<br>Total Awarded Amount: 59575053<br>GDP(million): 506505",
"State: RI<br>Total Awarded Amount: 4751919<br>GDP(million): 45663",
"State: SC<br>Total Awarded Amount: 9063478<br>GDP(million): 143585",
"State: SD<br>Total Awarded Amount: 3596551<br>GDP(million): 31380",
"State: TN<br>Total Awarded Amount: 18083590<br>GDP(million): 227505",
"State: TX<br>Total Awarded Amount: 48252344<br>GDP(million): 990054",
"State: UT<br>Total Awarded Amount: 6884351<br>GDP(million): 94475",
"State: VT<br>Total Awarded Amount: 6381133<br>GDP(million): 23539",
"State: VA<br>Total Awarded Amount: 18068081<br>GDP(million): 359273",
"State: WA<br>Total Awarded Amount: 23476750<br>GDP(million): 296403",
"State: WV<br>Total Awarded Amount: 927680<br>GDP(million): 53453",
"State: WI<br>Total Awarded Amount: 17075827<br>GDP(million): 226325",
"State: WY<br>Total Awarded Amount: 2210361<br>GDP(million): 27454]"],
  "type": "scattergeo", 
  "uid": "6e8b65"
}
trace17 = {
  "hoverinfo": "text", 
  "lat": [33.448, 29.954, 42.373611, 38.328732, 43.038902, 41.85, 39.768, 47.606, 33.792461, 39.29, 38.627, 44.979, 40.73061, 37.774, 37.339, 40.44, 34.052, 25.774, 29.763, 42.886], 
  "locationmode": "USA-states", 
  "lon": [-112.066667, -90.066667, -71.110556, -85.764771, -87.906471, -87.684722, -86.15, -122.333056, -118.185005, -76.616667, -90.197778, -93.266667, -73.935242, -122.416667, -121.9, -79.976389, -118.25, -80.208889, -95.383056, -78.849444], 
  "marker": {
    "color": "yellow", 
    "line": {
      "color": "orange", 
      "width": 1
    }, 
    "opacity": 0.1, 
    "size": [34.125, 28.875, 27.75, 27.75, 27.75, 27.5, 25, 14.75, 13.875, 13.125, 12.5, 12.5, 12.25, 12.25, 11.375, 11.375, 10.875, 9.625, 8.375, 7.75]
  }, 
  "showlegend": False, 
 "text": ["State: AL<br>Total Awarded Amount: 5743215<br>GDP(million):   156750",
"State: AK<br>Total Awarded Amount: 16189749<br>GDP(million): 40063",
"State: AZ<br>Total Awarded Amount: 19037687<br>GDP(million): 227358",
"State: AR<br>Total Awarded Amount: 1965330<br>GDP(million): 90319",
"State: CA<br>Total Awarded Amount: 74663752<br>GDP(million): 1766693",
"State: CO<br>Total Awarded Amount: 22235728<br>GDP(million): 220454",
"State: CT<br>Total Awarded Amount: 16501999<br>GDP(million): 210170",
"State: DE<br>Total Awarded Amount: 3857523<br>GDP(million): 53247",
"State: DC<br>Total Awarded Amount: 25424106<br>GDP(million): 83586",
"State: FL<br>Total Awarded Amount: 26600593<br>GDP(million): 700267",
"State: GA<br>Total Awarded Amount: 11216327<br>GDP(million): 388342",
"State: HI<br>Total Awarded Amount: 14427899<br>GDP(million): 58573",
"State: ID<br>Total Awarded Amount: 1961349<br>GDP(million): 47176",
"State: IL<br>Total Awarded Amount: 68112505<br>GDP(million): 586442",
"State: IN<br>Total Awarded Amount: 16377153<br>GDP(million): 245197",
"State: IA<br>Total Awarded Amount: 8493716<br>GDP(million): 123353",
"State: KS<br>Total Awarded Amount: 5764416<br>GDP(million): 104884",
"State: KY<br>Total Awarded Amount: 8022942<br>GDP(million): 143875",
"State: LA<br>Total Awarded Amount: 7978539<br>GDP(million): 199683",
"State: ME<br>Total Awarded Amount: 11177079<br>GDP(million): 46277",
"State: MD<br>Total Awarded Amount: 21671260<br>GDP(million): 263809",
"State: MA<br>Total Awarded Amount: 45976945<br>GDP(million): 345059",
"State: MI<br>Total Awarded Amount: 28799226<br>GDP(million): 395166",
"State: MN<br>Total Awarded Amount: 15325162<br>GDP(million): 243933",
"State: MS<br>Total Awarded Amount: 2787779<br>GDP(million): 81678",
"State: MO<br>Total Awarded Amount: 14911587<br>GDP(million): 224091",
"State: MT<br>Total Awarded Amount: 10424194<br>GDP(million): 30637",
"State: NE<br>Total Awarded Amount: 6600356<br>GDP(million): 73455",
"State: NV<br>Total Awarded Amount: 3677624<br>GDP(million): 118785",
"State: NH<br>Total Awarded Amount: 4797223<br>GDP(million): 57282",
"State: NJ<br>Total Awarded Amount: 11475362<br>GDP(million): 443148",
"State: NM<br>Total Awarded Amount: 10640574<br>GDP(million): 74403",
"State: NY<br>Total Awarded Amount: 105860170<br>GDP(million): 1023433",
"State: NC<br>Total Awarded Amount: 29992038<br>GDP(million): 357168",
"State: ND<br>Total Awarded Amount: 3071608<br>GDP(million): 24622",
"State: OH<br>Total Awarded Amount: 22015009<br>GDP(million): 467392",
"State: OK<br>Total Awarded Amount: 12405823<br>GDP(million): 125243",
"State: OR<br>Total Awarded Amount: 9556529<br>GDP(million): 147535",
"State: PA<br>Total Awarded Amount: 59575053<br>GDP(million): 506505",
"State: RI<br>Total Awarded Amount: 4751919<br>GDP(million): 45663",
"State: SC<br>Total Awarded Amount: 9063478<br>GDP(million): 143585",
"State: SD<br>Total Awarded Amount: 3596551<br>GDP(million): 31380",
"State: TN<br>Total Awarded Amount: 18083590<br>GDP(million): 227505",
"State: TX<br>Total Awarded Amount: 48252344<br>GDP(million): 990054",
"State: UT<br>Total Awarded Amount: 6884351<br>GDP(million): 94475",
"State: VT<br>Total Awarded Amount: 6381133<br>GDP(million): 23539",
"State: VA<br>Total Awarded Amount: 18068081<br>GDP(million): 359273",
"State: WA<br>Total Awarded Amount: 23476750<br>GDP(million): 296403",
"State: WV<br>Total Awarded Amount: 927680<br>GDP(million): 53453",
"State: WI<br>Total Awarded Amount: 17075827<br>GDP(million): 226325",
"State: WY<br>Total Awarded Amount: 2210361<br>GDP(million): 27454]"],
  "type": "scattergeo", 
  "uid": "cff0f4"
}
trace18 = {
  "hoverinfo": "text", 
  "lat": [33.448, 29.954, 42.373611, 38.328732, 43.038902, 41.85, 39.768, 47.606, 33.792461, 39.29, 38.627, 44.979, 40.73061, 37.774, 37.339, 40.44, 34.052, 25.774, 29.763, 42.886], 
  "locationmode": "USA-states", 
  "lon": [-112.066667, -90.066667, -71.110556, -85.764771, -87.906471, -87.684722, -86.15, -122.333056, -118.185005, -76.616667, -90.197778, -93.266667, -73.935242, -122.416667, -121.9, -79.976389, -118.25, -80.208889, -95.383056, -78.849444], 
  "marker": {
    "color": "yellow", 
    "line": {
      "color": "orange", 
      "width": 1
    }, 
    "opacity": 0.1, 
    "size": [34.125, 28.875, 27.75, 27.75, 27.75, 27.5, 25, 14.75, 13.875, 13.125, 12.5, 12.5, 12.25, 12.25, 11.375, 11.375, 10.875, 9.625, 8.375, 7.75]
  }, 
  "showlegend": False, 
 "text": ["State: AL<br>Total Awarded Amount: 5743215<br>GDP(million):   156750",
"State: AK<br>Total Awarded Amount: 16189749<br>GDP(million): 40063",
"State: AZ<br>Total Awarded Amount: 19037687<br>GDP(million): 227358",
"State: AR<br>Total Awarded Amount: 1965330<br>GDP(million): 90319",
"State: CA<br>Total Awarded Amount: 74663752<br>GDP(million): 1766693",
"State: CO<br>Total Awarded Amount: 22235728<br>GDP(million): 220454",
"State: CT<br>Total Awarded Amount: 16501999<br>GDP(million): 210170",
"State: DE<br>Total Awarded Amount: 3857523<br>GDP(million): 53247",
"State: DC<br>Total Awarded Amount: 25424106<br>GDP(million): 83586",
"State: FL<br>Total Awarded Amount: 26600593<br>GDP(million): 700267",
"State: GA<br>Total Awarded Amount: 11216327<br>GDP(million): 388342",
"State: HI<br>Total Awarded Amount: 14427899<br>GDP(million): 58573",
"State: ID<br>Total Awarded Amount: 1961349<br>GDP(million): 47176",
"State: IL<br>Total Awarded Amount: 68112505<br>GDP(million): 586442",
"State: IN<br>Total Awarded Amount: 16377153<br>GDP(million): 245197",
"State: IA<br>Total Awarded Amount: 8493716<br>GDP(million): 123353",
"State: KS<br>Total Awarded Amount: 5764416<br>GDP(million): 104884",
"State: KY<br>Total Awarded Amount: 8022942<br>GDP(million): 143875",
"State: LA<br>Total Awarded Amount: 7978539<br>GDP(million): 199683",
"State: ME<br>Total Awarded Amount: 11177079<br>GDP(million): 46277",
"State: MD<br>Total Awarded Amount: 21671260<br>GDP(million): 263809",
"State: MA<br>Total Awarded Amount: 45976945<br>GDP(million): 345059",
"State: MI<br>Total Awarded Amount: 28799226<br>GDP(million): 395166",
"State: MN<br>Total Awarded Amount: 15325162<br>GDP(million): 243933",
"State: MS<br>Total Awarded Amount: 2787779<br>GDP(million): 81678",
"State: MO<br>Total Awarded Amount: 14911587<br>GDP(million): 224091",
"State: MT<br>Total Awarded Amount: 10424194<br>GDP(million): 30637",
"State: NE<br>Total Awarded Amount: 6600356<br>GDP(million): 73455",
"State: NV<br>Total Awarded Amount: 3677624<br>GDP(million): 118785",
"State: NH<br>Total Awarded Amount: 4797223<br>GDP(million): 57282",
"State: NJ<br>Total Awarded Amount: 11475362<br>GDP(million): 443148",
"State: NM<br>Total Awarded Amount: 10640574<br>GDP(million): 74403",
"State: NY<br>Total Awarded Amount: 105860170<br>GDP(million): 1023433",
"State: NC<br>Total Awarded Amount: 29992038<br>GDP(million): 357168",
"State: ND<br>Total Awarded Amount: 3071608<br>GDP(million): 24622",
"State: OH<br>Total Awarded Amount: 22015009<br>GDP(million): 467392",
"State: OK<br>Total Awarded Amount: 12405823<br>GDP(million): 125243",
"State: OR<br>Total Awarded Amount: 9556529<br>GDP(million): 147535",
"State: PA<br>Total Awarded Amount: 59575053<br>GDP(million): 506505",
"State: RI<br>Total Awarded Amount: 4751919<br>GDP(million): 45663",
"State: SC<br>Total Awarded Amount: 9063478<br>GDP(million): 143585",
"State: SD<br>Total Awarded Amount: 3596551<br>GDP(million): 31380",
"State: TN<br>Total Awarded Amount: 18083590<br>GDP(million): 227505",
"State: TX<br>Total Awarded Amount: 48252344<br>GDP(million): 990054",
"State: UT<br>Total Awarded Amount: 6884351<br>GDP(million): 94475",
"State: VT<br>Total Awarded Amount: 6381133<br>GDP(million): 23539",
"State: VA<br>Total Awarded Amount: 18068081<br>GDP(million): 359273",
"State: WA<br>Total Awarded Amount: 23476750<br>GDP(million): 296403",
"State: WV<br>Total Awarded Amount: 927680<br>GDP(million): 53453",
"State: WI<br>Total Awarded Amount: 17075827<br>GDP(million): 226325",
"State: WY<br>Total Awarded Amount: 2210361<br>GDP(million): 27454]"],
  "type": "scattergeo", 
  "uid": "5fe304"
}
trace19 = {
  "hoverinfo": "text", 
  "lat": [33.448, 29.954, 42.373611, 38.328732, 43.038902, 41.85, 39.768, 47.606, 33.792461, 39.29, 38.627, 44.979, 40.73061, 37.774, 37.339, 40.44, 34.052, 25.774, 29.763, 42.886], 
  "locationmode": "USA-states", 
  "lon": [-112.066667, -90.066667, -71.110556, -85.764771, -87.906471, -87.684722, -86.15, -122.333056, -118.185005, -76.616667, -90.197778, -93.266667, -73.935242, -122.416667, -121.9, -79.976389, -118.25, -80.208889, -95.383056, -78.849444], 
  "marker": {
    "color": "yellow", 
    "line": {
      "color": "orange", 
      "width": 1
    }, 
    "opacity": 0.1, 
    "size": [34.125, 28.875, 27.75, 27.75, 27.75, 27.5, 25, 14.75, 13.875, 13.125, 12.5, 12.5, 12.25, 12.25, 11.375, 11.375, 10.875, 9.625, 8.375, 7.75]
  }, 
  "showlegend": False, 
 "text": ["State: AL<br>Total Awarded Amount: 5743215<br>GDP(million):   156750",
"State: AK<br>Total Awarded Amount: 16189749<br>GDP(million): 40063",
"State: AZ<br>Total Awarded Amount: 19037687<br>GDP(million): 227358",
"State: AR<br>Total Awarded Amount: 1965330<br>GDP(million): 90319",
"State: CA<br>Total Awarded Amount: 74663752<br>GDP(million): 1766693",
"State: CO<br>Total Awarded Amount: 22235728<br>GDP(million): 220454",
"State: CT<br>Total Awarded Amount: 16501999<br>GDP(million): 210170",
"State: DE<br>Total Awarded Amount: 3857523<br>GDP(million): 53247",
"State: DC<br>Total Awarded Amount: 25424106<br>GDP(million): 83586",
"State: FL<br>Total Awarded Amount: 26600593<br>GDP(million): 700267",
"State: GA<br>Total Awarded Amount: 11216327<br>GDP(million): 388342",
"State: HI<br>Total Awarded Amount: 14427899<br>GDP(million): 58573",
"State: ID<br>Total Awarded Amount: 1961349<br>GDP(million): 47176",
"State: IL<br>Total Awarded Amount: 68112505<br>GDP(million): 586442",
"State: IN<br>Total Awarded Amount: 16377153<br>GDP(million): 245197",
"State: IA<br>Total Awarded Amount: 8493716<br>GDP(million): 123353",
"State: KS<br>Total Awarded Amount: 5764416<br>GDP(million): 104884",
"State: KY<br>Total Awarded Amount: 8022942<br>GDP(million): 143875",
"State: LA<br>Total Awarded Amount: 7978539<br>GDP(million): 199683",
"State: ME<br>Total Awarded Amount: 11177079<br>GDP(million): 46277",
"State: MD<br>Total Awarded Amount: 21671260<br>GDP(million): 263809",
"State: MA<br>Total Awarded Amount: 45976945<br>GDP(million): 345059",
"State: MI<br>Total Awarded Amount: 28799226<br>GDP(million): 395166",
"State: MN<br>Total Awarded Amount: 15325162<br>GDP(million): 243933",
"State: MS<br>Total Awarded Amount: 2787779<br>GDP(million): 81678",
"State: MO<br>Total Awarded Amount: 14911587<br>GDP(million): 224091",
"State: MT<br>Total Awarded Amount: 10424194<br>GDP(million): 30637",
"State: NE<br>Total Awarded Amount: 6600356<br>GDP(million): 73455",
"State: NV<br>Total Awarded Amount: 3677624<br>GDP(million): 118785",
"State: NH<br>Total Awarded Amount: 4797223<br>GDP(million): 57282",
"State: NJ<br>Total Awarded Amount: 11475362<br>GDP(million): 443148",
"State: NM<br>Total Awarded Amount: 10640574<br>GDP(million): 74403",
"State: NY<br>Total Awarded Amount: 105860170<br>GDP(million): 1023433",
"State: NC<br>Total Awarded Amount: 29992038<br>GDP(million): 357168",
"State: ND<br>Total Awarded Amount: 3071608<br>GDP(million): 24622",
"State: OH<br>Total Awarded Amount: 22015009<br>GDP(million): 467392",
"State: OK<br>Total Awarded Amount: 12405823<br>GDP(million): 125243",
"State: OR<br>Total Awarded Amount: 9556529<br>GDP(million): 147535",
"State: PA<br>Total Awarded Amount: 59575053<br>GDP(million): 506505",
"State: RI<br>Total Awarded Amount: 4751919<br>GDP(million): 45663",
"State: SC<br>Total Awarded Amount: 9063478<br>GDP(million): 143585",
"State: SD<br>Total Awarded Amount: 3596551<br>GDP(million): 31380",
"State: TN<br>Total Awarded Amount: 18083590<br>GDP(million): 227505",
"State: TX<br>Total Awarded Amount: 48252344<br>GDP(million): 990054",
"State: UT<br>Total Awarded Amount: 6884351<br>GDP(million): 94475",
"State: VT<br>Total Awarded Amount: 6381133<br>GDP(million): 23539",
"State: VA<br>Total Awarded Amount: 18068081<br>GDP(million): 359273",
"State: WA<br>Total Awarded Amount: 23476750<br>GDP(million): 296403",
"State: WV<br>Total Awarded Amount: 927680<br>GDP(million): 53453",
"State: WI<br>Total Awarded Amount: 17075827<br>GDP(million): 226325",
"State: WY<br>Total Awarded Amount: 2210361<br>GDP(million): 27454]"],
  "type": "scattergeo", 
  "uid": "306bf0"
}
trace20 = {
  "hoverinfo": "text", 
  "lat": [33.448, 29.954, 42.373611, 38.328732, 43.038902, 41.85, 39.768, 47.606, 33.792461, 39.29, 38.627, 44.979, 40.73061, 37.774, 37.339, 40.44, 34.052, 25.774, 29.763, 42.886], 
  "locationmode": "USA-states", 
  "lon": [-112.066667, -90.066667, -71.110556, -85.764771, -87.906471, -87.684722, -86.15, -122.333056, -118.185005, -76.616667, -90.197778, -93.266667, -73.935242, -122.416667, -121.9, -79.976389, -118.25, -80.208889, -95.383056, -78.849444], 
  "marker": {
    "color": "yellow", 
    "line": {
      "color": "orange", 
      "width": 1
    }, 
    "opacity": 0.1, 
    "size": [34.125, 28.875, 27.75, 27.75, 27.75, 27.5, 25, 14.75, 13.875, 13.125, 12.5, 12.5, 12.25, 12.25, 11.375, 11.375, 10.875, 9.625, 8.375, 7.75]
  }, 
  "showlegend": False, 
 "text": ["State: AL<br>Total Awarded Amount: 5743215<br>GDP(million):   156750",
"State: AK<br>Total Awarded Amount: 16189749<br>GDP(million): 40063",
"State: AZ<br>Total Awarded Amount: 19037687<br>GDP(million): 227358",
"State: AR<br>Total Awarded Amount: 1965330<br>GDP(million): 90319",
"State: CA<br>Total Awarded Amount: 74663752<br>GDP(million): 1766693",
"State: CO<br>Total Awarded Amount: 22235728<br>GDP(million): 220454",
"State: CT<br>Total Awarded Amount: 16501999<br>GDP(million): 210170",
"State: DE<br>Total Awarded Amount: 3857523<br>GDP(million): 53247",
"State: DC<br>Total Awarded Amount: 25424106<br>GDP(million): 83586",
"State: FL<br>Total Awarded Amount: 26600593<br>GDP(million): 700267",
"State: GA<br>Total Awarded Amount: 11216327<br>GDP(million): 388342",
"State: HI<br>Total Awarded Amount: 14427899<br>GDP(million): 58573",
"State: ID<br>Total Awarded Amount: 1961349<br>GDP(million): 47176",
"State: IL<br>Total Awarded Amount: 68112505<br>GDP(million): 586442",
"State: IN<br>Total Awarded Amount: 16377153<br>GDP(million): 245197",
"State: IA<br>Total Awarded Amount: 8493716<br>GDP(million): 123353",
"State: KS<br>Total Awarded Amount: 5764416<br>GDP(million): 104884",
"State: KY<br>Total Awarded Amount: 8022942<br>GDP(million): 143875",
"State: LA<br>Total Awarded Amount: 7978539<br>GDP(million): 199683",
"State: ME<br>Total Awarded Amount: 11177079<br>GDP(million): 46277",
"State: MD<br>Total Awarded Amount: 21671260<br>GDP(million): 263809",
"State: MA<br>Total Awarded Amount: 45976945<br>GDP(million): 345059",
"State: MI<br>Total Awarded Amount: 28799226<br>GDP(million): 395166",
"State: MN<br>Total Awarded Amount: 15325162<br>GDP(million): 243933",
"State: MS<br>Total Awarded Amount: 2787779<br>GDP(million): 81678",
"State: MO<br>Total Awarded Amount: 14911587<br>GDP(million): 224091",
"State: MT<br>Total Awarded Amount: 10424194<br>GDP(million): 30637",
"State: NE<br>Total Awarded Amount: 6600356<br>GDP(million): 73455",
"State: NV<br>Total Awarded Amount: 3677624<br>GDP(million): 118785",
"State: NH<br>Total Awarded Amount: 4797223<br>GDP(million): 57282",
"State: NJ<br>Total Awarded Amount: 11475362<br>GDP(million): 443148",
"State: NM<br>Total Awarded Amount: 10640574<br>GDP(million): 74403",
"State: NY<br>Total Awarded Amount: 105860170<br>GDP(million): 1023433",
"State: NC<br>Total Awarded Amount: 29992038<br>GDP(million): 357168",
"State: ND<br>Total Awarded Amount: 3071608<br>GDP(million): 24622",
"State: OH<br>Total Awarded Amount: 22015009<br>GDP(million): 467392",
"State: OK<br>Total Awarded Amount: 12405823<br>GDP(million): 125243",
"State: OR<br>Total Awarded Amount: 9556529<br>GDP(million): 147535",
"State: PA<br>Total Awarded Amount: 59575053<br>GDP(million): 506505",
"State: RI<br>Total Awarded Amount: 4751919<br>GDP(million): 45663",
"State: SC<br>Total Awarded Amount: 9063478<br>GDP(million): 143585",
"State: SD<br>Total Awarded Amount: 3596551<br>GDP(million): 31380",
"State: TN<br>Total Awarded Amount: 18083590<br>GDP(million): 227505",
"State: TX<br>Total Awarded Amount: 48252344<br>GDP(million): 990054",
"State: UT<br>Total Awarded Amount: 6884351<br>GDP(million): 94475",
"State: VT<br>Total Awarded Amount: 6381133<br>GDP(million): 23539",
"State: VA<br>Total Awarded Amount: 18068081<br>GDP(million): 359273",
"State: WA<br>Total Awarded Amount: 23476750<br>GDP(million): 296403",
"State: WV<br>Total Awarded Amount: 927680<br>GDP(million): 53453",
"State: WI<br>Total Awarded Amount: 17075827<br>GDP(million): 226325",
"State: WY<br>Total Awarded Amount: 2210361<br>GDP(million): 27454]"],
  "type": "scattergeo", 
  "uid": "be8591"
}
trace21 = {
  "hoverinfo": "text", 
  "lat": [33.448, 29.954, 42.373611, 38.328732, 43.038902, 41.85, 39.768, 47.606, 33.792461, 39.29, 38.627, 44.979, 40.73061, 37.774, 37.339, 40.44, 34.052, 25.774, 29.763, 42.886], 
  "locationmode": "USA-states", 
  "lon": [-112.066667, -90.066667, -71.110556, -85.764771, -87.906471, -87.684722, -86.15, -122.333056, -118.185005, -76.616667, -90.197778, -93.266667, -73.935242, -122.416667, -121.9, -79.976389, -118.25, -80.208889, -95.383056, -78.849444], 
  "marker": {
    "color": "yellow", 
    "line": {
      "color": "orange", 
      "width": 1
    }, 
    "opacity": 0.1, 
    "size": [34.125, 28.875, 27.75, 27.75, 27.75, 27.5, 25, 14.75, 13.875, 13.125, 12.5, 12.5, 12.25, 12.25, 11.375, 11.375, 10.875, 9.625, 8.375, 7.75]
  }, 
  "showlegend": False, 
 "text": ["State: AL<br>Total Awarded Amount: 5743215<br>GDP(million):   156750",
"State: AK<br>Total Awarded Amount: 16189749<br>GDP(million): 40063",
"State: AZ<br>Total Awarded Amount: 19037687<br>GDP(million): 227358",
"State: AR<br>Total Awarded Amount: 1965330<br>GDP(million): 90319",
"State: CA<br>Total Awarded Amount: 74663752<br>GDP(million): 1766693",
"State: CO<br>Total Awarded Amount: 22235728<br>GDP(million): 220454",
"State: CT<br>Total Awarded Amount: 16501999<br>GDP(million): 210170",
"State: DE<br>Total Awarded Amount: 3857523<br>GDP(million): 53247",
"State: DC<br>Total Awarded Amount: 25424106<br>GDP(million): 83586",
"State: FL<br>Total Awarded Amount: 26600593<br>GDP(million): 700267",
"State: GA<br>Total Awarded Amount: 11216327<br>GDP(million): 388342",
"State: HI<br>Total Awarded Amount: 14427899<br>GDP(million): 58573",
"State: ID<br>Total Awarded Amount: 1961349<br>GDP(million): 47176",
"State: IL<br>Total Awarded Amount: 68112505<br>GDP(million): 586442",
"State: IN<br>Total Awarded Amount: 16377153<br>GDP(million): 245197",
"State: IA<br>Total Awarded Amount: 8493716<br>GDP(million): 123353",
"State: KS<br>Total Awarded Amount: 5764416<br>GDP(million): 104884",
"State: KY<br>Total Awarded Amount: 8022942<br>GDP(million): 143875",
"State: LA<br>Total Awarded Amount: 7978539<br>GDP(million): 199683",
"State: ME<br>Total Awarded Amount: 11177079<br>GDP(million): 46277",
"State: MD<br>Total Awarded Amount: 21671260<br>GDP(million): 263809",
"State: MA<br>Total Awarded Amount: 45976945<br>GDP(million): 345059",
"State: MI<br>Total Awarded Amount: 28799226<br>GDP(million): 395166",
"State: MN<br>Total Awarded Amount: 15325162<br>GDP(million): 243933",
"State: MS<br>Total Awarded Amount: 2787779<br>GDP(million): 81678",
"State: MO<br>Total Awarded Amount: 14911587<br>GDP(million): 224091",
"State: MT<br>Total Awarded Amount: 10424194<br>GDP(million): 30637",
"State: NE<br>Total Awarded Amount: 6600356<br>GDP(million): 73455",
"State: NV<br>Total Awarded Amount: 3677624<br>GDP(million): 118785",
"State: NH<br>Total Awarded Amount: 4797223<br>GDP(million): 57282",
"State: NJ<br>Total Awarded Amount: 11475362<br>GDP(million): 443148",
"State: NM<br>Total Awarded Amount: 10640574<br>GDP(million): 74403",
"State: NY<br>Total Awarded Amount: 105860170<br>GDP(million): 1023433",
"State: NC<br>Total Awarded Amount: 29992038<br>GDP(million): 357168",
"State: ND<br>Total Awarded Amount: 3071608<br>GDP(million): 24622",
"State: OH<br>Total Awarded Amount: 22015009<br>GDP(million): 467392",
"State: OK<br>Total Awarded Amount: 12405823<br>GDP(million): 125243",
"State: OR<br>Total Awarded Amount: 9556529<br>GDP(million): 147535",
"State: PA<br>Total Awarded Amount: 59575053<br>GDP(million): 506505",
"State: RI<br>Total Awarded Amount: 4751919<br>GDP(million): 45663",
"State: SC<br>Total Awarded Amount: 9063478<br>GDP(million): 143585",
"State: SD<br>Total Awarded Amount: 3596551<br>GDP(million): 31380",
"State: TN<br>Total Awarded Amount: 18083590<br>GDP(million): 227505",
"State: TX<br>Total Awarded Amount: 48252344<br>GDP(million): 990054",
"State: UT<br>Total Awarded Amount: 6884351<br>GDP(million): 94475",
"State: VT<br>Total Awarded Amount: 6381133<br>GDP(million): 23539",
"State: VA<br>Total Awarded Amount: 18068081<br>GDP(million): 359273",
"State: WA<br>Total Awarded Amount: 23476750<br>GDP(million): 296403",
"State: WV<br>Total Awarded Amount: 927680<br>GDP(million): 53453",
"State: WI<br>Total Awarded Amount: 17075827<br>GDP(million): 226325",
"State: WY<br>Total Awarded Amount: 2210361<br>GDP(million): 27454]"],
  "type": "scattergeo", 
  "uid": "d83ee5"
}

In [49]:
data = Data([trace1, trace2, trace3, trace4, trace5, trace6, trace7, trace8, trace9, trace10, trace11, trace12, trace13, trace14, trace15, trace16, trace17, trace18, trace19, trace20, trace21])
layout = {
  "autosize": True, 
  "geo": {
    "countrycolor": "rgb(255,255,255)", 
    "countrywidth": 1, 
    "lakecolor": "rgb(255,255,255)", 
    "landcolor": "rgb(255,255,255)", 
    "projection": {"type": "albers usa"}, 
    "scope": "usa", 
    "showlakes": True, 
    "showland": True, 
    "subunitcolor": "rgb(255,255,255)", 
    "subunitwidth": 1
  }, 
  "height": 532, 
  "legend": {
    "bgcolor": "#E2E2E2", 
    "bordercolor": "#FFFFFF", 
    "borderwidth": 2, 
    "font": {
      "color": "#000", 
      "family": "sans-serif", 
      "size": 12
    }
  }, 
  "title": "Female-to-Male Proportion of CoBRA Readership in the United States <br>(Circle size indicates proportion of female-to-male letter writers in the top 20 cities)", 
  "width": 1188
}

In [69]:
data

[{'colorbar': {'outlinecolor': 'white',
   'showexponent': 'last',
   'title': 'GDP Distribution (State-level)',
   'x': 0,
   'y': 0.5},
  'hoverinfo': 'text',
  'locationmode': 'USA-states',
  'locations': ['AL',
   'AK',
   'AZ',
   'AR',
   'CA',
   'CO',
   'CT',
   'DE',
   'FL',
   'GA',
   'HI',
   'ID',
   'IL',
   'IN',
   'IA',
   'KS',
   'KY',
   'LA',
   'ME',
   'MD',
   'MA',
   'MI',
   'MN',
   'MS',
   'MO',
   'MT',
   'NE',
   'NV',
   'NH',
   'NJ',
   'NM',
   'NY',
   'NC',
   'ND',
   'OH',
   'OK',
   'OR',
   'PA',
   'RI',
   'SC',
   'SD',
   'TN',
   'TX',
   'UT',
   'VT',
   'VA',
   'WA',
   'WV',
   'WI',
   'WY'],
  'marker': {'line': {'color': 'rgb(255,255,255)', 'width': 1}},
  'name': 'States',
  'text': ['State: AL<br>Total Awarded Amount: 5743215<br>GDP(million):   156750',
   'State: AK<br>Total Awarded Amount: 16189749<br>GDP(million): 40063',
   'State: AZ<br>Total Awarded Amount: 19037687<br>GDP(million): 227358',
   'State: AR<br>Total Awarded Amount: 1965330<br>GDP(million): 90319',
   'State: CA<br>Total Awarded Amount: 74663752<br>GDP(million): 1766693',
   'State: CO<br>Total Awarded Amount: 22235728<br>GDP(million): 220454',
   'State: CT<br>Total Awarded Amount: 16501999<br>GDP(million): 210170',
   'State: DE<br>Total Awarded Amount: 3857523<br>GDP(million): 53247',
   'State: DC<br>Total Awarded Amount: 25424106<br>GDP(million): 83586',
   'State: FL<br>Total Awarded Amount: 26600593<br>GDP(million): 700267',
   'State: GA<br>Total Awarded Amount: 11216327<br>GDP(million): 388342',
   'State: HI<br>Total Awarded Amount: 14427899<br>GDP(million): 58573',
   'State: ID<br>Total Awarded Amount: 1961349<br>GDP(million): 47176',
   'State: IL<br>Total Awarded Amount: 68112505<br>GDP(million): 586442',
   'State: IN<br>Total Awarded Amount: 16377153<br>GDP(million): 245197',
   'State: IA<br>Total Awarded Amount: 8493716<br>GDP(million): 123353',
   'State: KS<br>Total Awarded Amount: 5764416<br>GDP(million): 104884',
   'State: KY<br>Total Awarded Amount: 8022942<br>GDP(million): 143875',
   'State: LA<br>Total Awarded Amount: 7978539<br>GDP(million): 199683',
   'State: ME<br>Total Awarded Amount: 11177079<br>GDP(million): 46277',
   'State: MD<br>Total Awarded Amount: 21671260<br>GDP(million): 263809',
   'State: MA<br>Total Awarded Amount: 45976945<br>GDP(million): 345059',
   'State: MI<br>Total Awarded Amount: 28799226<br>GDP(million): 395166',
   'State: MN<br>Total Awarded Amount: 15325162<br>GDP(million): 243933',
   'State: MS<br>Total Awarded Amount: 2787779<br>GDP(million): 81678',
   'State: MO<br>Total Awarded Amount: 14911587<br>GDP(million): 224091',
   'State: MT<br>Total Awarded Amount: 10424194<br>GDP(million): 30637',
   'State: NE<br>Total Awarded Amount: 6600356<br>GDP(million): 73455',
   'State: NV<br>Total Awarded Amount: 3677624<br>GDP(million): 118785',
   'State: NH<br>Total Awarded Amount: 4797223<br>GDP(million): 57282',
   'State: NJ<br>Total Awarded Amount: 11475362<br>GDP(million): 443148',
   'State: NM<br>Total Awarded Amount: 10640574<br>GDP(million): 74403',
   'State: NY<br>Total Awarded Amount: 105860170<br>GDP(million): 1023433',
   'State: NC<br>Total Awarded Amount: 29992038<br>GDP(million): 357168',
   'State: ND<br>Total Awarded Amount: 3071608<br>GDP(million): 24622',
   'State: OH<br>Total Awarded Amount: 22015009<br>GDP(million): 467392',
   'State: OK<br>Total Awarded Amount: 12405823<br>GDP(million): 125243',
   'State: OR<br>Total Awarded Amount: 9556529<br>GDP(million): 147535',
   'State: PA<br>Total Awarded Amount: 59575053<br>GDP(million): 506505',
   'State: RI<br>Total Awarded Amount: 4751919<br>GDP(million): 45663',
   'State: SC<br>Total Awarded Amount: 9063478<br>GDP(million): 143585',
   'State: SD<br>Total Awarded Amount: 3596551<br>GDP(million): 31380',
   'State: TN<br>Total Awarded Amount: 18083590<br>GDP(million): 227505',
   'State: TX<br>Total Awarded Amount: 48252344<br>GDP(million): 990054',
   'State: UT<br>Total Awarded Amount: 6884351<br>GDP(million): 94475',
   'State: VT<br>Total Awarded Amount: 6381133<br>GDP(million): 23539',
   'State: VA<br>Total Awarded Amount: 18068081<br>GDP(million): 359273',
   'State: WA<br>Total Awarded Amount: 23476750<br>GDP(million): 296403',
   'State: WV<br>Total Awarded Amount: 927680<br>GDP(million): 53453',
   'State: WI<br>Total Awarded Amount: 17075827<br>GDP(million): 226325',
   'State: WY<br>Total Awarded Amount: 2210361<br>GDP(million): 27454]'],
  'type': 'choropleth',
  'uid': 'dafa1f',
  'z': [156750,
   40063,
   227358,
   90319,
   1766693,
   220454,
   210170,
   53247,
   83586,
   700267,
   388342,
   58573,
   47176,
   586442,
   245197,
   123353,
   104884,
   143875,
   199683,
   46277,
   263809,
   345059,
   395166,
   243933,
   81678,
   224091,
   30637,
   73455,
   118785,
   57282,
   443148,
   74403,
   1023433,
   357168,
   24622,
   467392,
   125243,
   147535,
   506505,
   45663,
   143585,
   31380,
   227505,
   990054,
   94475,
   23539,
   359273,
   296403,
   53453,
   226325,
   27454],
  'zmax': 0.375,
  'zmin': 0},
 {'hoverinfo': 'text',
  'lat': [33.448,
   29.954,
   42.373611,
   38.328732,
   43.038902,
   41.85,
   39.768,
   47.606,
   33.792461,
   39.29,
   38.627,
   44.979,
   40.73061,
   37.774,
   37.339,
   40.44,
   34.052,
   25.774,
   29.763,
   42.886],
  'locationmode': 'USA-states',
  'lon': [-112.066667,
   -90.066667,
   -71.110556,
   -85.764771,
   -87.906471,
   -87.684722,
   -86.15,
   -122.333056,
   -118.185005,
   -76.616667,
   -90.197778,
   -93.266667,
   -73.935242,
   -122.416667,
   -121.9,
   -79.976389,
   -118.25,
   -80.208889,
   -95.383056,
   -78.849444],
  'marker': {'color': 'yellow',
   'line': {'color': 'orange', 'width': 1},
   'opacity': 0.1,
   'size': [34.125,
    28.875,
    27.75,
    27.75,
    27.75,
    27.5,
    25,
    14.75,
    13.875,
    13.125,
    12.5,
    12.5,
    12.25,
    12.25,
    11.375,
    11.375,
    10.875,
    9.625,
    8.375,
    7.75]},
  'showlegend': False,
  'text': ['State: AL<br>Total Awarded Amount: 5743215<br>GDP(million):   156750',
   'State: AK<br>Total Awarded Amount: 16189749<br>GDP(million): 40063',
   'State: AZ<br>Total Awarded Amount: 19037687<br>GDP(million): 227358',
   'State: AR<br>Total Awarded Amount: 1965330<br>GDP(million): 90319',
   'State: CA<br>Total Awarded Amount: 74663752<br>GDP(million): 1766693',
   'State: CO<br>Total Awarded Amount: 22235728<br>GDP(million): 220454',
   'State: CT<br>Total Awarded Amount: 16501999<br>GDP(million): 210170',
   'State: DE<br>Total Awarded Amount: 3857523<br>GDP(million): 53247',
   'State: DC<br>Total Awarded Amount: 25424106<br>GDP(million): 83586',
   'State: FL<br>Total Awarded Amount: 26600593<br>GDP(million): 700267',
   'State: GA<br>Total Awarded Amount: 11216327<br>GDP(million): 388342',
   'State: HI<br>Total Awarded Amount: 14427899<br>GDP(million): 58573',
   'State: ID<br>Total Awarded Amount: 1961349<br>GDP(million): 47176',
   'State: IL<br>Total Awarded Amount: 68112505<br>GDP(million): 586442',
   'State: IN<br>Total Awarded Amount: 16377153<br>GDP(million): 245197',
   'State: IA<br>Total Awarded Amount: 8493716<br>GDP(million): 123353',
   'State: KS<br>Total Awarded Amount: 5764416<br>GDP(million): 104884',
   'State: KY<br>Total Awarded Amount: 8022942<br>GDP(million): 143875',
   'State: LA<br>Total Awarded Amount: 7978539<br>GDP(million): 199683',
   'State: ME<br>Total Awarded Amount: 11177079<br>GDP(million): 46277',
   'State: MD<br>Total Awarded Amount: 21671260<br>GDP(million): 263809',
   'State: MA<br>Total Awarded Amount: 45976945<br>GDP(million): 345059',
   'State: MI<br>Total Awarded Amount: 28799226<br>GDP(million): 395166',
   'State: MN<br>Total Awarded Amount: 15325162<br>GDP(million): 243933',
   'State: MS<br>Total Awarded Amount: 2787779<br>GDP(million): 81678',
   'State: MO<br>Total Awarded Amount: 14911587<br>GDP(million): 224091',
   'State: MT<br>Total Awarded Amount: 10424194<br>GDP(million): 30637',
   'State: NE<br>Total Awarded Amount: 6600356<br>GDP(million): 73455',
   'State: NV<br>Total Awarded Amount: 3677624<br>GDP(million): 118785',
   'State: NH<br>Total Awarded Amount: 4797223<br>GDP(million): 57282',
   'State: NJ<br>Total Awarded Amount: 11475362<br>GDP(million): 443148',
   'State: NM<br>Total Awarded Amount: 10640574<br>GDP(million): 74403',
   'State: NY<br>Total Awarded Amount: 105860170<br>GDP(million): 1023433',
   'State: NC<br>Total Awarded Amount: 29992038<br>GDP(million): 357168',
   'State: ND<br>Total Awarded Amount: 3071608<br>GDP(million): 24622',
   'State: OH<br>Total Awarded Amount: 22015009<br>GDP(million): 467392',
   'State: OK<br>Total Awarded Amount: 12405823<br>GDP(million): 125243',
   'State: OR<br>Total Awarded Amount: 9556529<br>GDP(million): 147535',
   'State: PA<br>Total Awarded Amount: 59575053<br>GDP(million): 506505',
   'State: RI<br>Total Awarded Amount: 4751919<br>GDP(million): 45663',
   'State: SC<br>Total Awarded Amount: 9063478<br>GDP(million): 143585',
   'State: SD<br>Total Awarded Amount: 3596551<br>GDP(million): 31380',
   'State: TN<br>Total Awarded Amount: 18083590<br>GDP(million): 227505',
   'State: TX<br>Total Awarded Amount: 48252344<br>GDP(million): 990054',
   'State: UT<br>Total Awarded Amount: 6884351<br>GDP(million): 94475',
   'State: VT<br>Total Awarded Amount: 6381133<br>GDP(million): 23539',
   'State: VA<br>Total Awarded Amount: 18068081<br>GDP(million): 359273',
   'State: WA<br>Total Awarded Amount: 23476750<br>GDP(million): 296403',
   'State: WV<br>Total Awarded Amount: 927680<br>GDP(million): 53453',
   'State: WI<br>Total Awarded Amount: 17075827<br>GDP(million): 226325',
   'State: WY<br>Total Awarded Amount: 2210361<br>GDP(million): 27454]'],
  'type': 'scattergeo',
  'uid': '637ddb'},
 {'hoverinfo': 'text',
  'lat': [33.448,
   29.954,
   42.373611,
   38.328732,
   43.038902,
   41.85,
   39.768,
   47.606,
   33.792461,
   39.29,
   38.627,
   44.979,
   40.73061,
   37.774,
   37.339,
   40.44,
   34.052,
   25.774,
   29.763,
   42.886],
  'locationmode': 'USA-states',
  'lon': [-112.066667,
   -90.066667,
   -71.110556,
   -85.764771,
   -87.906471,
   -87.684722,
   -86.15,
   -122.333056,
   -118.185005,
   -76.616667,
   -90.197778,
   -93.266667,
   -73.935242,
   -122.416667,
   -121.9,
   -79.976389,
   -118.25,
   -80.208889,
   -95.383056,
   -78.849444],
  'marker': {'color': 'yellow',
   'line': {'color': 'orange', 'width': 1},
   'opacity': 0.1,
   'size': [34.125,
    28.875,
    27.75,
    27.75,
    27.75,
    27.5,
    25,
    14.75,
    13.875,
    13.125,
    12.5,
    12.5,
    12.25,
    12.25,
    11.375,
    11.375,
    10.875,
    9.625,
    8.375,
    7.75]},
  'showlegend': False,
  'text': ['State: AL<br>Total Awarded Amount: 5743215<br>GDP(million):   156750',
   'State: AK<br>Total Awarded Amount: 16189749<br>GDP(million): 40063',
   'State: AZ<br>Total Awarded Amount: 19037687<br>GDP(million): 227358',
   'State: AR<br>Total Awarded Amount: 1965330<br>GDP(million): 90319',
   'State: CA<br>Total Awarded Amount: 74663752<br>GDP(million): 1766693',
   'State: CO<br>Total Awarded Amount: 22235728<br>GDP(million): 220454',
   'State: CT<br>Total Awarded Amount: 16501999<br>GDP(million): 210170',
   'State: DE<br>Total Awarded Amount: 3857523<br>GDP(million): 53247',
   'State: DC<br>Total Awarded Amount: 25424106<br>GDP(million): 83586',
   'State: FL<br>Total Awarded Amount: 26600593<br>GDP(million): 700267',
   'State: GA<br>Total Awarded Amount: 11216327<br>GDP(million): 388342',
   'State: HI<br>Total Awarded Amount: 14427899<br>GDP(million): 58573',
   'State: ID<br>Total Awarded Amount: 1961349<br>GDP(million): 47176',
   'State: IL<br>Total Awarded Amount: 68112505<br>GDP(million): 586442',
   'State: IN<br>Total Awarded Amount: 16377153<br>GDP(million): 245197',
   'State: IA<br>Total Awarded Amount: 8493716<br>GDP(million): 123353',
   'State: KS<br>Total Awarded Amount: 5764416<br>GDP(million): 104884',
   'State: KY<br>Total Awarded Amount: 8022942<br>GDP(million): 143875',
   'State: LA<br>Total Awarded Amount: 7978539<br>GDP(million): 199683',
   'State: ME<br>Total Awarded Amount: 11177079<br>GDP(million): 46277',
   'State: MD<br>Total Awarded Amount: 21671260<br>GDP(million): 263809',
   'State: MA<br>Total Awarded Amount: 45976945<br>GDP(million): 345059',
   'State: MI<br>Total Awarded Amount: 28799226<br>GDP(million): 395166',
   'State: MN<br>Total Awarded Amount: 15325162<br>GDP(million): 243933',
   'State: MS<br>Total Awarded Amount: 2787779<br>GDP(million): 81678',
   'State: MO<br>Total Awarded Amount: 14911587<br>GDP(million): 224091',
   'State: MT<br>Total Awarded Amount: 10424194<br>GDP(million): 30637',
   'State: NE<br>Total Awarded Amount: 6600356<br>GDP(million): 73455',
   'State: NV<br>Total Awarded Amount: 3677624<br>GDP(million): 118785',
   'State: NH<br>Total Awarded Amount: 4797223<br>GDP(million): 57282',
   'State: NJ<br>Total Awarded Amount: 11475362<br>GDP(million): 443148',
   'State: NM<br>Total Awarded Amount: 10640574<br>GDP(million): 74403',
   'State: NY<br>Total Awarded Amount: 105860170<br>GDP(million): 1023433',
   'State: NC<br>Total Awarded Amount: 29992038<br>GDP(million): 357168',
   'State: ND<br>Total Awarded Amount: 3071608<br>GDP(million): 24622',
   'State: OH<br>Total Awarded Amount: 22015009<br>GDP(million): 467392',
   'State: OK<br>Total Awarded Amount: 12405823<br>GDP(million): 125243',
   'State: OR<br>Total Awarded Amount: 9556529<br>GDP(million): 147535',
   'State: PA<br>Total Awarded Amount: 59575053<br>GDP(million): 506505',
   'State: RI<br>Total Awarded Amount: 4751919<br>GDP(million): 45663',
   'State: SC<br>Total Awarded Amount: 9063478<br>GDP(million): 143585',
   'State: SD<br>Total Awarded Amount: 3596551<br>GDP(million): 31380',
   'State: TN<br>Total Awarded Amount: 18083590<br>GDP(million): 227505',
   'State: TX<br>Total Awarded Amount: 48252344<br>GDP(million): 990054',
   'State: UT<br>Total Awarded Amount: 6884351<br>GDP(million): 94475',
   'State: VT<br>Total Awarded Amount: 6381133<br>GDP(million): 23539',
   'State: VA<br>Total Awarded Amount: 18068081<br>GDP(million): 359273',
   'State: WA<br>Total Awarded Amount: 23476750<br>GDP(million): 296403',
   'State: WV<br>Total Awarded Amount: 927680<br>GDP(million): 53453',
   'State: WI<br>Total Awarded Amount: 17075827<br>GDP(million): 226325',
   'State: WY<br>Total Awarded Amount: 2210361<br>GDP(million): 27454]'],
  'type': 'scattergeo',
  'uid': '2bdf0d'},
 {'hoverinfo': 'text',
  'lat': [33.448,
   29.954,
   42.373611,
   38.328732,
   43.038902,
   41.85,
   39.768,
   47.606,
   33.792461,
   39.29,
   38.627,
   44.979,
   40.73061,
   37.774,
   37.339,
   40.44,
   34.052,
   25.774,
   29.763,
   42.886],
  'locationmode': 'USA-states',
  'lon': [-112.066667,
   -90.066667,
   -71.110556,
   -85.764771,
   -87.906471,
   -87.684722,
   -86.15,
   -122.333056,
   -118.185005,
   -76.616667,
   -90.197778,
   -93.266667,
   -73.935242,
   -122.416667,
   -121.9,
   -79.976389,
   -118.25,
   -80.208889,
   -95.383056,
   -78.849444],
  'marker': {'color': 'yellow',
   'line': {'color': 'orange', 'width': 1},
   'opacity': 0.1,
   'size': [34.125,
    28.875,
    27.75,
    27.75,
    27.75,
    27.5,
    25,
    14.75,
    13.875,
    13.125,
    12.5,
    12.5,
    12.25,
    12.25,
    11.375,
    11.375,
    10.875,
    9.625,
    8.375,
    7.75]},
  'showlegend': False,
  'text': ['State: AL<br>Total Awarded Amount: 5743215<br>GDP(million):   156750',
   'State: AK<br>Total Awarded Amount: 16189749<br>GDP(million): 40063',
   'State: AZ<br>Total Awarded Amount: 19037687<br>GDP(million): 227358',
   'State: AR<br>Total Awarded Amount: 1965330<br>GDP(million): 90319',
   'State: CA<br>Total Awarded Amount: 74663752<br>GDP(million): 1766693',
   'State: CO<br>Total Awarded Amount: 22235728<br>GDP(million): 220454',
   'State: CT<br>Total Awarded Amount: 16501999<br>GDP(million): 210170',
   'State: DE<br>Total Awarded Amount: 3857523<br>GDP(million): 53247',
   'State: DC<br>Total Awarded Amount: 25424106<br>GDP(million): 83586',
   'State: FL<br>Total Awarded Amount: 26600593<br>GDP(million): 700267',
   'State: GA<br>Total Awarded Amount: 11216327<br>GDP(million): 388342',
   'State: HI<br>Total Awarded Amount: 14427899<br>GDP(million): 58573',
   'State: ID<br>Total Awarded Amount: 1961349<br>GDP(million): 47176',
   'State: IL<br>Total Awarded Amount: 68112505<br>GDP(million): 586442',
   'State: IN<br>Total Awarded Amount: 16377153<br>GDP(million): 245197',
   'State: IA<br>Total Awarded Amount: 8493716<br>GDP(million): 123353',
   'State: KS<br>Total Awarded Amount: 5764416<br>GDP(million): 104884',
   'State: KY<br>Total Awarded Amount: 8022942<br>GDP(million): 143875',
   'State: LA<br>Total Awarded Amount: 7978539<br>GDP(million): 199683',
   'State: ME<br>Total Awarded Amount: 11177079<br>GDP(million): 46277',
   'State: MD<br>Total Awarded Amount: 21671260<br>GDP(million): 263809',
   'State: MA<br>Total Awarded Amount: 45976945<br>GDP(million): 345059',
   'State: MI<br>Total Awarded Amount: 28799226<br>GDP(million): 395166',
   'State: MN<br>Total Awarded Amount: 15325162<br>GDP(million): 243933',
   'State: MS<br>Total Awarded Amount: 2787779<br>GDP(million): 81678',
   'State: MO<br>Total Awarded Amount: 14911587<br>GDP(million): 224091',
   'State: MT<br>Total Awarded Amount: 10424194<br>GDP(million): 30637',
   'State: NE<br>Total Awarded Amount: 6600356<br>GDP(million): 73455',
   'State: NV<br>Total Awarded Amount: 3677624<br>GDP(million): 118785',
   'State: NH<br>Total Awarded Amount: 4797223<br>GDP(million): 57282',
   'State: NJ<br>Total Awarded Amount: 11475362<br>GDP(million): 443148',
   'State: NM<br>Total Awarded Amount: 10640574<br>GDP(million): 74403',
   'State: NY<br>Total Awarded Amount: 105860170<br>GDP(million): 1023433',
   'State: NC<br>Total Awarded Amount: 29992038<br>GDP(million): 357168',
   'State: ND<br>Total Awarded Amount: 3071608<br>GDP(million): 24622',
   'State: OH<br>Total Awarded Amount: 22015009<br>GDP(million): 467392',
   'State: OK<br>Total Awarded Amount: 12405823<br>GDP(million): 125243',
   'State: OR<br>Total Awarded Amount: 9556529<br>GDP(million): 147535',
   'State: PA<br>Total Awarded Amount: 59575053<br>GDP(million): 506505',
   'State: RI<br>Total Awarded Amount: 4751919<br>GDP(million): 45663',
   'State: SC<br>Total Awarded Amount: 9063478<br>GDP(million): 143585',
   'State: SD<br>Total Awarded Amount: 3596551<br>GDP(million): 31380',
   'State: TN<br>Total Awarded Amount: 18083590<br>GDP(million): 227505',
   'State: TX<br>Total Awarded Amount: 48252344<br>GDP(million): 990054',
   'State: UT<br>Total Awarded Amount: 6884351<br>GDP(million): 94475',
   'State: VT<br>Total Awarded Amount: 6381133<br>GDP(million): 23539',
   'State: VA<br>Total Awarded Amount: 18068081<br>GDP(million): 359273',
   'State: WA<br>Total Awarded Amount: 23476750<br>GDP(million): 296403',
   'State: WV<br>Total Awarded Amount: 927680<br>GDP(million): 53453',
   'State: WI<br>Total Awarded Amount: 17075827<br>GDP(million): 226325',
   'State: WY<br>Total Awarded Amount: 2210361<br>GDP(million): 27454]'],
  'type': 'scattergeo',
  'uid': '6ce964'},
 {'hoverinfo': 'text',
  'lat': [33.448,
   29.954,
   42.373611,
   38.328732,
   43.038902,
   41.85,
   39.768,
   47.606,
   33.792461,
   39.29,
   38.627,
   44.979,
   40.73061,
   37.774,
   37.339,
   40.44,
   34.052,
   25.774,
   29.763,
   42.886],
  'locationmode': 'USA-states',
  'lon': [-112.066667,
   -90.066667,
   -71.110556,
   -85.764771,
   -87.906471,
   -87.684722,
   -86.15,
   -122.333056,
   -118.185005,
   -76.616667,
   -90.197778,
   -93.266667,
   -73.935242,
   -122.416667,
   -121.9,
   -79.976389,
   -118.25,
   -80.208889,
   -95.383056,
   -78.849444],
  'marker': {'color': 'yellow',
   'line': {'color': 'orange', 'width': 1},

In [70]:
layout

{'autosize': True,
 'geo': {'countrycolor': 'rgb(255,255,255)',
  'countrywidth': 1,
  'lakecolor': 'rgb(255,255,255)',
  'landcolor': 'rgb(255,255,255)',
  'projection': {'type': 'albers usa'},
  'scope': 'usa',
  'showlakes': True,
  'showland': True,
  'subunitcolor': 'rgb(255,255,255)',
  'subunitwidth': 1},
 'height': 532,
 'legend': {'bgcolor': '#E2E2E2',
  'bordercolor': '#FFFFFF',
  'borderwidth': 2,
  'font': {'color': '#000', 'family': 'sans-serif', 'size': 12}},
 'title': 'Female-to-Male Proportion of CoBRA Readership in the United States <br>(Circle size indicates proportion of female-to-male letter writers in the top 20 cities)',
 'width': 1188}

In [71]:
fig = Figure(data=data, layout=layout)

In [73]:
py.iplot( fig, validate=False, filename='d3-bubble-map-populations' )

PlotlyRequestError: Aw, snap! You tried to use our API as the user 'Username', but the supplied API key doesn't match our records. You can view your API key at plot.ly/settings.

You're most likely getting this message because your local credentials file isn't synced with the Plotly server you're communicating with.

Go to plot.ly/<language>/getting-started (e.g., plot.ly/python/getting-started) for more information.

Make sure that you're logged in as Username.

Need help? Please try searching Plotly's <a href='http://stackoverflow.com/questions/tagged/plotly'>Stack Overflow channel</a>.